In [2]:
import pandas as pd

- A Pandas Series is a one-dimensional labeled array (single column), whereas a Pandas DataFrame is a two-dimensional labeled table made of multiple Series (columns).

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie"]
}

df = pd.DataFrame(data)
age_series = [24,27,22]

df

      Name
0    Alice
1      Bob
2  Charlie

In [4]:
age_series

[24, 27, 22]

In [5]:
import seaborn as sns

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
# Colum selection 

# single column
total_bill = df['total_bill']
# multiple column
subset_cols = df[["total_bill", "tip", "sex"]]

# Row selection 
filtered_rows = df[df["total_bill"] > 20]
filtered_multi = df[(df["total_bill"]>20) & (df["sex"] == "Male")]

print(subset_cols.head())
print(filtered_rows.head())
print(filtered_multi.head())

   total_bill   tip     sex
0       16.99  1.01  Female
1       10.34  1.66    Male
2       21.01  3.50    Male
3       23.68  3.31    Male
4       24.59  3.61  Female
   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4
    total_bill   tip   sex smoker  day    time  size
2        21.01  3.50  Male     No  Sun  Dinner     3
3        23.68  3.31  Male     No  Sun  Dinner     2
5        25.29  4.71  Male     No  Sun  Dinner     4
7        26.88  3.12  Male     No  Sun  Dinner     4
15       21.58  3.92  Male     No  Sun  Dinner     2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [8]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

- df.info() shows the structure and data types of a DataFrame (columns, non-null counts, memory), while df.describe() shows statistical summaries of the data (count, mean, std, min, max, etc.).

## percentile 
- A percentile is a value below which a given percentage of the data falls (for example, the 75th percentile means 75% of the observations are at or below that value).

# loc and iloc

In [9]:
# Rows by label, columns by name 
df.loc[0:3 , ["total_bill", "tip"]]

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31

- With .loc, columns must be specified using column labels (names), not integer positions.

- loc slicing is inclusive of both start and end labels

- iloc slicing is exclusive of the end index (like normal Python slicing)

In [10]:
# Filter rows using condition with column selection 
df.loc[df["sex"] == "Female", ["total_bill", "tip"]] # loc[rows ,columns]

     total_bill   tip
0         16.99  1.01
4         24.59  3.61
11        35.26  5.00
14        14.83  3.02
16        10.33  1.67
..          ...   ...
226       10.09  2.00
229       22.12  2.88
238       35.83  4.67
240       27.18  2.00
243       18.78  3.00

[87 rows x 2 columns]

In [11]:
# Rows by integer position, columns by position
df.iloc[0:4, 0:2]

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31

In [12]:
# Single row and column by position
df.iloc[5,1]

np.float64(4.71)

# Sorting in pandas

In [13]:
# ascending
df.sort_values(by="total_bill").head()

     total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
172        7.25  5.15    Male    Yes   Sun  Dinner     2
149        7.51  2.00    Male     No  Thur   Lunch     2

In [14]:
# descending 
df.sort_values(by="total_bill", ascending=False).head()

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [15]:
# sort by multiple columns 
df.sort_values(by=["sex","total_bill"], ascending=[True, False])

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
156       48.17   5.00    Male     No   Sun  Dinner     6
182       45.35   3.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
135        8.51   1.25  Female     No  Thur   Lunch     2
145        8.35   1.50  Female     No  Thur   Lunch     2
111        7.25   1.00  Female     No   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 7 columns]

In [16]:
df['sex'].dtype

CategoricalDtype(categories=['Male', 'Female'], ordered=False, categories_dtype=object)

- The reason Male comes first and not Female when sorting is because of the dtype. It is categorical even though ordered=False pandas still uses categorical order.
- If it was string it would have sorted lexicographically and Female would come first.

- Categorical dtype in Pandas is a data type used to represent columns with a fixed set of repeating values (categories), storing them efficiently and allowing controlled ordering (e.g., Male/Female, Low/Medium/High).

# Handling missing values

In [17]:
df = sns.load_dataset('titanic')

df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [18]:
df.dropna()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [19]:
# Drop where specific column is missing
df.dropna(subset=['age'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [20]:
# drop column with missing values 
df.dropna(axis=1)

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,male,1,0,7.2500,Third,man,True,no,False
1,1,1,female,1,0,71.2833,First,woman,False,yes,False
2,1,3,female,0,0,7.9250,Third,woman,False,yes,True
3,1,1,female,1,0,53.1000,First,woman,False,yes,False
4,0,3,male,0,0,8.0500,Third,man,True,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,Second,man,True,no,True
887,1,1,female,0,0,30.0000,First,woman,False,yes,True
888,0,3,female,1,2,23.4500,Third,woman,False,no,False
889,1,1,male,0,0,30.0000,First,man,True,yes,True
890,0,3,male,0,0,7.7500,Third,man,True,no,True

In [21]:
# fill with a constant 
# df.fillna(0)
num_cols = df.select_dtypes(include="number")
df[num_cols.columns] = num_cols.fillna(0)

In [22]:
# Fill with mean / median / mode
df["age"].fillna(df["age"].mean(), inplace=True)

/tmp/ipykernel_532857/170281142.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

In [23]:
df["age"].fillna(df["age"].median(), inplace=True)

/tmp/ipykernel_532857/3040546416.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].median(), inplace=True)

In [24]:
df["age"].fillna(df["age"].mode(), inplace=True)

/tmp/ipykernel_532857/222073962.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mode(), inplace=True)

In [25]:
# Forward fill and Backward fill
df.fillna(method="ffill")

/tmp/ipykernel_532857/1430930571.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,C,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,0.0,1,2,23.4500,S,Third,woman,False,B,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True

In [26]:
df.fillna(method="bfill")

/tmp/ipykernel_532857/3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,0.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# Type conversion

In [27]:
print('age type',df['age'].dtype)
print('fare type',df['fare'].dtype)

age type float64
fare type float64

In [28]:
df['age'] = df['age'].astype(int)
df['fare'] = df['fare'].astype(float)

In [29]:
# Safe numeric conversion = to_numeric() invalid value --> NaN 
df['age'] = pd.to_numeric(df["age"], errors="coerce")
# coerce means “force conversion” by replacing any non-numeric or invalid value with NaN instead of raising an error.

In [30]:
df["sex"] = df["sex"].astype(str)

In [31]:
df["sex"] = df["sex"].astype("category")

In [32]:
# With custom order
df["sex"] = pd.Categorical(
    df["sex"],
    categories=["Male", "Female"],
    ordered=True
)
""" 
pd.Categorical(..., ordered=True)
converts a column into a memory-efficient,
ordered label type, allowing Pandas to sort 
and compare values using your defined logical order
instead of alphabetical order."""

' \npd.Categorical(..., ordered=True)\nconverts a column into a memory-efficient,\nordered label type, allowing Pandas to sort \nand compare values using your defined logical order\ninstead of alphabetical order.'

In [33]:
# convert to datetime

# df['date'] = pd.to_datetime(df['date'], errors="coerce")

In [34]:
# convert multiple columns at once 
df = df.astype({
    "age":"float",
    "fare": "float",
    "sex":  "category"
})

In [35]:
# convert entire Dataframe
df = df.apply(pd.to_numeric, errors='ignore')

/tmp/ipykernel_532857/217598150.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

# Categorical data handling

In [36]:
df = sns.load_dataset('tips')

In [37]:
df['sex'] = df['sex'].astype("category")

In [38]:
# with explicit categories and order 
df['sex'] = pd.Categorical(
    df['sex'],
    categories=["Male","Female"],
    ordered=True
)

In [39]:
# inspect categorical data 
df["sex"].dtype

CategoricalDtype(categories=['Male', 'Female'], ordered=True, categories_dtype=object)

In [40]:
df["sex"].cat.categories

Index(['Male', 'Female'], dtype='object')

     .cat is the Categorical Accessor.

Think of it as:

    - “Give me tools that only make sense for categorical data.”

In [41]:
df["sex"].cat.ordered

True

In [42]:
df["sex"].cat.codes

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Length: 244, dtype: int8

This is the integer encoding of the categories.


    Male    → 0
    Female  → 1
    NaN     → -1

## Add /Remove Categories

In [43]:
df["sex"] = df["sex"].cat.add_categories("Unknown")

In [44]:
df["sex"].cat.categories

Index(['Male', 'Female', 'Unknown'], dtype='object')

In [45]:
df["sex"] = df["sex"].cat.remove_categories("Unknown")

In [46]:
df["sex"].cat.categories

Index(['Male', 'Female'], dtype='object')

## Handling missing values in categorical columns

In [47]:
df = sns.load_dataset('titanic')

In [48]:
df["deck"].dtype

CategoricalDtype(categories=['A', 'B', 'C', 'D', 'E', 'F', 'G'], ordered=False, categories_dtype=object)

In [49]:
df["deck"].isna().sum()

np.int64(688)

In [50]:
# df["deck"].fillna("Unknown") Throws error if unknown is not a category
# add category then fill 
df["deck"] = df["deck"].cat.add_categories("Unknown")
df["deck"] = df["deck"].fillna("Unknown")

In [51]:
# remove values instead 
df = df.dropna(subset=["deck"])

In [52]:
# convert to string less alternative 
df["deck"] = df["deck"].astype(str)
df["deck"] = df["deck"].fillna("Unknown")

In [53]:
df["deck"].isna().sum()

np.int64(0)

# grouby and agg

In [54]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [55]:
df.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

1. df.groupby("sex")

- Returns a DataFrameGroupBy object

- No aggregation is computed yet

2. ["survived"]

- Selects a column

- Returns a SeriesGroupBy object

3. .mean()

- Triggers computation

- Produces a concrete Series

In [56]:
df.groupby("sex")

- grouby() creates a GroupBy object, which is a lazy, iterable view over grouped data.

- #### What is a GroupBy object?

A GroupBy object is:

    Lazy (no computation until aggregation)

    Iterable (you can loop over it)

    Not a generator

In [57]:
# Groupby multiple columns 
df.groupby(["sex", "class"])["survived"].mean()

/tmp/ipykernel_532857/1528755850.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex", "class"])["survived"].mean()

sex     class
female  First     0.968085
        Second    0.921053
        Third     0.500000
male    First     0.368852
        Second    0.157407
        Third     0.135447
Name: survived, dtype: float64

In [58]:
# Using agg()

df.groupby('class').agg(
    avg_age = ("age", "mean"),
    max_age=("age", "max"),
    avg_fare=("fare", "mean"),
    count=("fare", "count")
)

/tmp/ipykernel_532857/803727316.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class').agg(

          avg_age  max_age   avg_fare  count
class
First   38.233441     80.0  84.154687    216
Second  29.877630     70.0  20.662183    184
Third   25.140620     74.0  13.675550    491

- Syntax 
```
df.groupby(group_cols).agg(
    output_col_name = (input_col_name, aggregation_function),
    ...
)
```

# Pandas GroupBy Aggregation – Cheat Sheet

## Basic Pattern
```python
df.groupby("group_col").agg(
    out_col=("source_col", "agg_func")
)
````

---

## Core Aggregations (Most Used)

* `mean`
* `sum`
* `min`
* `max`
* `count`   # excludes NaN
* `size`    # includes NaN
* `median`
* `std`
* `var`
* `nunique`

---

## Descriptive / Distribution

* `quantile`
* `idxmin`
* `idxmax`
* `sem`
* `prod`

--- 


* **`quantile(q)`** — returns the value below which *q × 100%* of the data falls
* **`idxmin`** — returns the index label of the minimum value in the group
* **`idxmax`** — returns the index label of the maximum value in the group
* **`sem`** — returns the standard error of the mean *(std / √n)*
* **`prod`** — returns the product of all values in the group


---

## Boolean

* `any`
* `all`

---

## Categorical / String

* `first`
* `last`
* `unique`
* `value_counts`

---

## Valid Function Types

```python
("age", "mean")        # pandas string
("age", np.mean)      # NumPy
("age", len)          # Python builtin
("age", lambda x: x.max() - x.min())  # custom
```

---

## Multiple Aggregations

```python
df.groupby("class").agg(
    avg_age=("age", "mean"),
    max_age=("age", "max"),
    cnt=("fare", "count")
)
```

---

## count vs size

| Function | Counts NaN |
| -------- | ---------- |
| count    | ❌ No       |
| size     | ✅ Yes      |

---

## Rules

* Each aggregation returns **one scalar**
* Output column names are **mandatory**
* Same column can be aggregated multiple times
* Computation is **lazy** until `.agg()` is called

---

## Mental Model

`groupby().agg()` = **SQL GROUP BY + SELECT**

```sql
SELECT class, AVG(age), MAX(age)
FROM df
GROUP BY class;
```

```

In [59]:
# Multiple aggregation on same column
df.groupby("sex")["age"].agg(["mean", "median", "min", "max"])

             mean  median   min   max
sex
female  27.915709    27.0  0.75  63.0
male    30.726645    29.0  0.42  80.0

In [62]:
# Rest Index (Flat DataFrame)
df.groupby("sex")["survived"].mean().reset_index()

      sex  survived
0  female  0.742038
1    male  0.188908

- reset_index() converts the group-by index (sex) back into a regular column, turning the result from an indexed Series into a standard DataFrame.

In [ ]:
# common mistake

# df.groupby("sex").mean()

Mental model
| Step        | Meaning                     |
| ----------- | --------------------------- |
| `groupby()` | Split data into groups      |
| `agg()`     | Apply aggregation functions |
| Result      | One row per group           |

# Merging and Joining

In [63]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"]
})

orders = pd.DataFrame({
    "customer_id": [1, 1, 2],
    "order_amount": [250, 450, 300]
})

In [64]:
customers

   customer_id     name
0            1    Alice
1            2      Bob
2            3  Charlie

In [65]:
orders

   customer_id  order_amount
0            1           250
1            1           450
2            2           300

In [70]:
# # Merging 
pd.merge(customers, orders, on="customer_id")
# Only matching customer_ids
# # Drops customers with no orders

   customer_id   name  order_amount
0            1  Alice           250
1            1  Alice           450
2            2    Bob           300

In [71]:
# left join 
pd.merge(customers, orders, on="customer_id", how="left")

   customer_id     name  order_amount
0            1    Alice         250.0
1            1    Alice         450.0
2            2      Bob         300.0
3            3  Charlie           NaN

In [72]:
# Right join
pd.merge(customers, orders, on="customer_id", how="right")

   customer_id   name  order_amount
0            1  Alice           250
1            1  Alice           450
2            2    Bob           300

In [73]:
#outer join 
pd.merge(customers, orders, on="customer_id", how="outer")
# Keeps all rows from both tables

   customer_id     name  order_amount
0            1    Alice         250.0
1            1    Alice         450.0
2            2      Bob         300.0
3            3  Charlie           NaN

In [75]:
# Merge with different column names 
pd.merge(
    customers,
    orders,
    left_on="customer_id",
    right_on="customer_id"
)
# (Useful when column names differ.)

   customer_id   name  order_amount
0            1  Alice           250
1            1  Alice           450
2            2    Bob           300

# Join using index join()

In [78]:
customers.set_index("customer_id").join(
    orders.set_index("customer_id"),
    how="left"
)
# join() works on index
# merge() works on columns

                name  order_amount
customer_id
1              Alice         250.0
1              Alice         450.0
2                Bob         300.0
3            Charlie           NaN

In [79]:
# Many to one merge(Very common) 

pd.merge(orders, customers, on="customer_id")

# Many orders -> one customer 
# No duplication issues if keys are correct

   customer_id  order_amount   name
0            1           250  Alice
1            1           450  Alice
2            2           300    Bob

In [80]:
# Check merge correctness 
pd.merge(customers, orders, on="customer_id", validate="one_to_many")
# Helps catch bug early

   customer_id   name  order_amount
0            1  Alice           250
1            1  Alice           450
2            2    Bob           300

- merge() joins DataFrames using columns, while join() joins DataFrames using the index (often making the join key the index)

# One hot encoding with pandas

In [81]:
df = sns.load_dataset("titanic")

In [84]:
encoded = pd.get_dummies(df["sex"], dtype=int)
encoded.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [86]:
# one hot encoding multiple columns 
df_encoded = pd.get_dummies(df, columns=["sex", "embarked"], dtype=int)
df_encoded

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,0,1,0,0,1
1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,1,0,1,0,0
2,1,3,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,1,0,0,0,1
3,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,1,0,0,0,1
4,0,3,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,Second,man,True,NaN,Southampton,no,True,0,1,0,0,1
887,1,1,19.0,0,0,30.0000,First,woman,False,B,Southampton,yes,True,1,0,0,0,1
888,0,3,NaN,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False,1,0,0,0,1
889,1,1,26.0,0,0,30.0000,First,man,True,C,Cherbourg,yes,True,0,1,1,0,0
890,0,3,32.0,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True,0,1,0,1,0

# Train/Test prepration with titatnic dataset

In [87]:
df = sns.load_dataset("titanic")

In [88]:
X = df[["age", "fare", "sex", "embarked"]]
y = df["survived"]

In [94]:
X.info() , X.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       714 non-null    float64
 1   fare      891 non-null    float64
 2   sex       891 non-null    object
 3   embarked  889 non-null    object
dtypes: float64(2), object(2)
memory usage: 28.0+ KB

(None,
 age         177
 fare          0
 sex           0
 embarked      2
 dtype: int64)

In [95]:
y.info(), y.isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: survived
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB

(None, np.int64(0))

In [96]:
# encode categorical variables
X = pd.get_dummies(X, columns=["sex","embarked"], dtype=int)

In [97]:
from sklearn.model_selection import train_test_split
X_train, X_text, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)