# Logistic Regression in Machine Learning


## What is Logistic Regression?

**Logistic Regression** is a **supervised machine learning algorithm** used for **classification problems**.
Unlike **Linear Regression**, which predicts continuous numerical values, Logistic Regression predicts the **probability** that a given input belongs to a particular class.

It is primarily used for **binary classification**, where the output belongs to one of two categories such as:

* Yes / No
* True / False
* 0 / 1

Logistic Regression uses the **sigmoid (logistic) function** to map predictions to probability values between **0 and 1**.

---

## Types of Logistic Regression

Logistic Regression can be categorized into three types based on the nature of the **dependent (target) variable**:

### 1. Binomial Logistic Regression

* Used when the dependent variable has **two possible outcomes**
* Examples:

  * Yes / No
  * Pass / Fail
  * 0 / 1
* This is the **most common** form of logistic regression and is used for binary classification problems.

### 2. Multinomial Logistic Regression

* Used when the dependent variable has **three or more categories**
* The categories **do not have an inherent order**
* Example:

  * Classifying animals into *cat*, *dog*, or *sheep*
* It extends binary logistic regression to handle **multiple classes**.

### 3. Ordinal Logistic Regression

* Used when the dependent variable has **three or more ordered categories**
* The categories follow a **natural ranking**
* Example:

  * Low → Medium → High
* The model takes the **order of the categories** into account.

---

## Assumptions of Logistic Regression

To apply Logistic Regression correctly, the following assumptions should be satisfied:

1. **Independent observations**

   * Each data point must be independent of others
   * There should be no correlation between input samples

2. **Binary dependent variable**

   * The target variable should be binary (0 or 1)
   * For more than two classes, **Softmax-based models** are typically used

3. **Linearity between predictors and log odds**

   * There should be a linear relationship between independent variables and the **log-odds** of the dependent variable

4. **No extreme outliers**

   * Outliers can significantly affect coefficient estimation and model performance

5. **Large sample size**

   * Logistic Regression performs better with a sufficiently large dataset to ensure stable and reliable results

---

## Understanding the Sigmoid Function

![Image](https://upload.wikimedia.org/wikipedia/commons/8/88/Logistic-curve.svg)

![Image](https://media.licdn.com/dms/image/v2/C5612AQFdFHPAEGDmMQ/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1520207453657?e=2147483647\&t=JZOh2Mee_tQowCle6b302IhJRR87iHgleWsulc44a58\&v=beta)

![Image](https://media.geeksforgeeks.org/wp-content/uploads/20250131185746649092/Sigmoid-Activation-Function.png)

1. The **sigmoid function** is a key component of Logistic Regression. It converts the raw model output into a **probability value between 0 and 1**.

2. The function maps any real-valued number to the range **(0, 1)** and produces an **S-shaped curve**, also known as the *logistic curve*.

3. Since probabilities must lie between 0 and 1, the sigmoid function is ideal for classification tasks.

---

## Classification Decision Using Threshold

In Logistic Regression, a **threshold value** (commonly **0.5**) is used to assign class labels:

* If `sigmoid(output) ≥ 0.5` → **Class 1**
* If `sigmoid(output) < 0.5` → **Class 0**

This threshold-based decision process converts continuous probability values into **discrete class predictions**, making the results interpretable and actionable.

---

# Maximum Likelihood Estimation (MLE) in Logistic Regression

## Why Maximum Likelihood is Used

In **Linear Regression**, model parameters are estimated using **Least Squares** because the output is continuous and normally distributed.

In **Logistic Regression**, the output is **binary (0 or 1)**, so:
- Errors are **not normally distributed**
- Least Squares is **not appropriate**

Instead, Logistic Regression uses **Maximum Likelihood Estimation (MLE)** to estimate the model parameters.

---

## Step 1: Logistic Model Definition

Logistic Regression models the **probability of class 1** as:

$$p(y=1|x) = \sigma(z) = \frac{1}{1 + e^{-z}}$$

where:

$$z = w^T x + b$$

- $w$ = weight vector
- $x$ = feature vector
- $b$ = bias term
- $\sigma(\cdot)$ = sigmoid function

---

## Step 2: Bernoulli Distribution Assumption

Since the target variable $y \in \{0,1\}$, we assume:

$$y \sim \text{Bernoulli}(p)$$

Probability mass function:

$$P(y|x) = p^y (1 - p)^{(1 - y)}$$

This single equation handles **both classes**:
- If $y = 1$: probability = $p$
- If $y = 0$: probability = $1 - p$

---

## Step 3: Likelihood Function

For a dataset with $n$ independent samples:

$$\mathcal{L}(w, b) = \prod_{i=1}^{n} p_i^{y_i}(1 - p_i)^{(1 - y_i)}$$

where:

$$p_i = \sigma(w^T x_i + b)$$

**Goal of MLE:**
> Choose $w$ and $b$ that maximize the likelihood

---

## Step 4: Log-Likelihood (Optimization-Friendly Form)

Taking the logarithm converts the product into a sum:

$$\log \mathcal{L}(w,b) = \sum_{i=1}^{n} \left[ y_i \log(p_i) + (1 - y_i)\log(1 - p_i) \right]$$

This is called the **log-likelihood function**.

---

## Step 5: Loss Function (Binary Cross-Entropy)

In practice, we **minimize loss**, not maximize likelihood. So we take **negative log-likelihood**:

$$\mathcal{L}_{loss} = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(p_i) + (1 - y_i)\log(1 - p_i) \right]$$

This is known as:
- **Log Loss**
- **Binary Cross-Entropy Loss**

---

## Step 6: Parameter Optimization (Gradient Descent)

There is **no closed-form solution** for logistic regression parameters. So we use **iterative optimization**, typically:
- Gradient Descent
- Stochastic Gradient Descent (SGD)
- Newton's Method (e.g., L-BFGS)

**Gradient of the loss:**

$$\frac{\partial \mathcal{L}}{\partial w} = \frac{1}{n} \sum_{i=1}^{n} (p_i - y_i)x_i$$

$$\frac{\partial \mathcal{L}}{\partial b} = \frac{1}{n} \sum_{i=1}^{n} (p_i - y_i)$$

**Update rule:**

$$w := w - \alpha \frac{\partial \mathcal{L}}{\partial w}$$

$$b := b - \alpha \frac{\partial \mathcal{L}}{\partial b}$$

where $\alpha$ is the learning rate.

---

## Intuition Behind MLE in Logistic Regression

- If the model predicts **high probability for correct class** → loss decreases
- If it predicts **high probability for wrong class** → loss increases sharply
- This forces the model to push decision boundaries correctly

---

## Key Interview One-Liners

- Logistic Regression uses **Maximum Likelihood Estimation**, not least squares.
- The target variable is modeled using a **Bernoulli distribution**.
- The optimization objective is **log-likelihood**, equivalent to minimizing **binary cross-entropy loss**.
- Parameters are learned using **iterative optimization** methods like gradient descent.

# Logistic Regression (Code)

In [80]:
from sklearn.datasets import load_breast_cancer
import pandas as pd 

data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = pd.Series(data.target).map(
    {0:data.target_names[0], 1:data.target_names[1]}
)

df.head()

   mean radius  mean texture  ...  worst fractal dimension     target
0        17.99         10.38  ...                  0.11890  malignant
1        20.57         17.77  ...                  0.08902  malignant
2        19.69         21.25  ...                  0.08758  malignant
3        11.42         20.38  ...                  0.17300  malignant
4        20.29         14.34  ...                  0.07678  malignant

[5 rows x 31 columns]

In [81]:
data.target_names[0]

np.str_('malignant')

In [82]:
from sklearn.model_selection import train_test_split 

X = df.drop(columns="target")
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
X_train.shape, X_test.shape

((455, 30), (114, 30))

stratify=y is used when the target is categorical (classification).

Why stratify=y matters:

- Medical data is often imbalanced

- Missing a class in test data makes evaluation invalid

- Especially dangerous in healthcare ML

In [83]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

target
benign       0.631579
malignant    0.368421
Name: proportion, dtype: float64

In [84]:
from sklearn.linear_model import LogisticRegressionCV

log_reg_cv = LogisticRegressionCV(
    Cs=10,
    cv=5,
    max_iter=10000,
    scoring="accuracy",
    n_jobs=-1
)
# in medical data instead of     scoring="accuracy",
# -> use F1 or Recall or precision

**`Cs`**: *Defines the search space for regularization strength—LogisticRegressionCV tests multiple logarithmically spaced `C` values (e.g., ~1e-4 to 1e4) via cross-validation and selects the best one.*

In [85]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Fit Logistic Regression with cross-validation
log_reg_cv.fit(X_train, y_train)

/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)

LogisticRegressionCV(cv=5, max_iter=10000, n_jobs=-1, scoring='accuracy')

In [86]:
# 2. Predict on unseen test data
y_pred = log_reg_cv.predict(X_test)
# 3. Best regularization strength chosen by CV
best_C = log_reg_cv.C_[0]   # single value because this is binary classification
print(f"Best C chosen by CV: {best_C:.4f}")
print("------------------------------")
# 4. Accuracy on test data
print("Test accuracy:", accuracy_score(y_test, y_pred))
print("------------------------------")
# 5. Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("------------------------------")
# 6. Precision, Recall, F1-score
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("------------------------------")

Best C chosen by CV: 1291.5497
------------------------------
Test accuracy: 0.9473684210526315
------------------------------

Confusion Matrix:
[[70  2]
 [ 4 38]]
------------------------------

Classification Report:
              precision    recall  f1-score   support

      benign       0.95      0.97      0.96        72
   malignant       0.95      0.90      0.93        42

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

------------------------------

### Logistic Regression – Model Insights

- **Best C ≈ 1291.55** → Very weak regularization, indicating the data is close to linearly separable and benefits from a more flexible model.
- **Test Accuracy ≈ 94.7%** → Strong generalization performance on unseen data; realistic and not indicative of overfitting.
- **Confusion Matrix Insight**:
  - 70 benign correctly classified
  - 2 benign falsely flagged as malignant (false positives)
  - 38 malignant correctly detected
  - **4 malignant missed (false negatives)** — the most critical error in medical diagnosis.
- **Precision (~95%)** → When the model predicts malignant, it is correct most of the time.
- **Recall (malignant = 90%)** → The model detects 9 out of 10 cancer cases; ~10% are missed.
- **F1-score (malignant = 0.93)** → Good balance between precision and recall.
- **Overall Insight** → High accuracy masks a key risk: missed malignant cases. In medical settings, recall should be prioritized over accuracy.

In [87]:
"""y_num = y.map({"benign": 0, "malignant": 1})

Then scoring = "recall" works automatically
But you lose semantic clarity, which is why 

from sklearn.metrics import make_scorer, recall_score

recall_malignant = make_scorer(
    recall_score,
    pos_label="malignant"
)
"""
from sklearn.metrics import make_scorer, recall_score

recall_malignant = make_scorer(
    recall_score,
    pos_label="malignant"
)


log_reg_cv_recall = LogisticRegressionCV(
    Cs=10,
    cv=5,
    max_iter=10000,
    scoring=recall_malignant,
    n_jobs=-1,
    class_weight={"malignant":2, "benign":1}
)
# class weight added for reducing FN
# Increase weight for malignant to prioritize recall (reduce FN)

### Recall Tuning – Key Concepts

- **`recall_score`**: Measures how many actual positive cases were correctly identified  
  $$
  \text{Recall} = \frac{TP}{TP + FN}
  $$
  In medical data, this answers: *“Out of all cancer cases, how many did we detect?”*

- **`make_scorer`**: Wraps a metric function so scikit-learn can use it during cross-validation, allowing customization (e.g., defining the positive class).

- **`pos_label="malignant"`**: Explicitly marks **malignant (cancer)** as the positive class, which is critical when labels are strings (`"benign"`, `"malignant"`).

- **Why not rely on `0/1` labels?**
  - `0/1` works, but loses semantic clarity.
  - String labels are safer and more interpretable in medical ML, provided `pos_label` is defined.

- **Best practice**: Keep human-readable labels and explicitly specify the positive class when optimizing recall, precision, or F1-score.

**`pos_label`** = the **positive class label** (the class you care most about)

- It tells the metric which class is treated as **“positive”**
- Recall, precision, and F1 are always computed **with respect to this class**
- In medical datasets:
  - `pos_label = "malignant"` (disease present)
  - `pos_label = "benign"` would be wrong

**Example**
- `pos_label="malignant"` → *“Out of all cancer cases, how many did we detect?”*

**Rule of thumb**
> Always explicitly set `pos_label` when labels are strings or when the positive class matters.

In [88]:
log_reg_cv_recall.fit(X_train, y_train)

/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)
/home/aromal/anaconda3/envs/study/lib/python3.11/multiprocessing/queues.py:122: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  return _ForkingPickler.loads(res)

LogisticRegressionCV(class_weight={'benign': 1, 'malignant': 2}, cv=5,
                     max_iter=10000, n_jobs=-1,
                     scoring=make_scorer(recall_score, response_method='predict', pos_label=malignant))

In [89]:

# 1. Predict on test data
y_pred_recall = log_reg_cv_recall.predict(X_test)

# 2. Best C chosen by recall-based CV
best_C_recall = log_reg_cv_recall.C_[0]
print(f"Best C chosen by CV (Recall-optimized): {best_C_recall:.4f}")

# 3. Accuracy (will likely drop slightly)
print("Test accuracy:", accuracy_score(y_test, y_pred_recall))

# 4. Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_recall))

# 5. Precision, Recall, F1
print("\nClassification Report:")
print(classification_report(y_test, y_pred_recall))

Best C chosen by CV (Recall-optimized): 21.5443
Test accuracy: 0.9473684210526315

Confusion Matrix:
[[70  2]
 [ 4 38]]

Classification Report:
              precision    recall  f1-score   support

      benign       0.95      0.97      0.96        72
   malignant       0.95      0.90      0.93        42

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

### Regularization Parameter `C` in Logistic Regression

- **`C` controls how strongly the model is regularized**
- It is the **inverse of regularization strength**

$$
\text{Loss} + \frac{1}{C} \times \text{Penalty}
$$

| Value of `C` | Effect |
|-------------|--------|
| **Small `C`** | Strong regularization → simpler model (risk of underfitting) |
| **Large `C`** | Weak regularization → more flexible model (risk of overfitting) |

When a model is inside a `Pipeline`, its learned attributes (e.g., `C_`) must be accessed via `pipeline.named_steps["step_name"]` because the pipeline is a container, not the estimator itself.

### Insight: Why False Negatives Did Not Reduce

- Adding `class_weight` and optimizing for recall **changed the model’s regularization (C)** but **did not change final predictions**.
- Logistic Regression still uses a **fixed decision threshold (0.5)** to convert probabilities into class labels.
- The missed malignant cases have predicted probabilities **below 0.5**, even after weighting.
- **Class weights reshape probabilities**, but **threshold controls the final decision**.
- Therefore, **false negatives remain unchanged**.

**Key takeaway**:  
> In Logistic Regression, reducing false negatives requires **lowering the decision threshold**, not just tuning `C` or using class weights.

# Logistic Regression with Pipeline, with scaling

In [90]:

from sklearn.datasets import load_breast_cancer
import pandas as pd 

data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = pd.Series(data.target).map(
    {0:data.target_names[0], 1:data.target_names[1]}
)

df.head()

   mean radius  mean texture  ...  worst fractal dimension     target
0        17.99         10.38  ...                  0.11890  malignant
1        20.57         17.77  ...                  0.08902  malignant
2        19.69         21.25  ...                  0.08758  malignant
3        11.42         20.38  ...                  0.17300  malignant
4        20.29         14.34  ...                  0.07678  malignant

[5 rows x 31 columns]

In [91]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df.drop(columns="target")
y = df["target"]

# Train–test split (stratified for classification)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train.shape, X_test.shape

((455, 30), (114, 30))

In [92]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV

# Build pipeline: scaling happens inside CV (no data leakage)
logistic_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("logistic_regression", LogisticRegressionCV(
        Cs=10,
        cv=5,
        max_iter=10000,
        scoring="accuracy",
        n_jobs=-1
    ))
])

# Fit pipeline (CV + final training happen here)
logistic_pipeline.fit(X_train, y_train)

/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/home/aromal/anaconda3/envs/study/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()),
                ('logistic_regression',
                 LogisticRegressionCV(cv=5, max_iter=10000, n_jobs=-1,
                                      scoring='accuracy'))])

In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predict using the trained pipeline
y_pred = logistic_pipeline.predict(X_test)

# Extract best C from the LogisticRegressionCV inside the pipeline
best_C = logistic_pipeline.named_steps["logistic_regression"].C_[0]
print(f"Best C chosen by CV: {best_C:.4f}")

# Accuracy
print("Logistic Test accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Best C chosen by CV: 2.7826
Logistic Test accuracy: 0.9736842105263158

Confusion Matrix:
[[71  1]
 [ 2 40]]

Classification Report:
              precision    recall  f1-score   support

      benign       0.97      0.99      0.98        72
   malignant       0.98      0.95      0.96        42

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [94]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

log_accuracy = accuracy_score(y_test, y_pred)
log_precision = precision_score(y_test, y_pred, pos_label="malignant")
log_recall = recall_score(y_test, y_pred, pos_label="malignant")
log_f1 = f1_score(y_test, y_pred, pos_label="malignant")

print("Logistic Regression Metrics")
print("Accuracy :", log_accuracy)
print("Precision:", log_precision)
print("Recall   :", log_recall)
print("F1-score :", log_f1)

Logistic Regression Metrics
Accuracy : 0.9736842105263158
Precision: 0.975609756097561
Recall   : 0.9523809523809523
F1-score : 0.963855421686747

### Logistic Regression (Pipeline + Scaling) — Key Insights

- **Best C ≈ 2.78**  
  → Moderate regularization after proper feature scaling; the model no longer needs extreme flexibility.

- **Test Accuracy ≈ 97.4%**  
  → Clear improvement over the unscaled version; scaling significantly benefits Logistic Regression.

- **Confusion Matrix Insight**:
  - 71 benign correctly classified
  - 1 benign falsely flagged as malignant
  - **40 malignant correctly detected**
  - **Only 2 malignant missed (FN)** → improved medical safety

- **Malignant Recall = 0.95**  
  → The model now detects **95% of cancer cases**, a strong result for a linear model.

- **Overall Interpretation**:
  - Proper **scaling + pipeline** leads to better optimization, better `C`, and fewer false negatives.
  - This is a **near-optimal baseline** for Logistic Regression on this dataset.

**Bottom line**:  
> Feature scaling inside a pipeline is critical for Logistic Regression; it improves both accuracy and malignant recall, making the model more reliable for medical classification.

# KNN


---

## K-Nearest Neighbors (KNN) Algorithm — Detailed Explanation

### 1. Definition

**K-Nearest Neighbors (KNN)** is a **supervised, non-parametric, instance-based (lazy learning)** algorithm used for **classification and regression**.
It makes predictions based on the **similarity (distance)** between a new data point and the training samples.

---

### 2. Key Characteristics

* **Lazy learner**: No explicit training phase; all computation happens during prediction.
* **Non-parametric**: Does not assume any underlying data distribution.
* **Distance-based**: Relies on distance metrics to measure similarity.

---

### 3. Working Principle (Step-by-Step)

#### Step 1: Choose the value of *k*

* `k` = number of nearest neighbors to consider.
* Small `k` → sensitive to noise (overfitting).
* Large `k` → smoother decision boundary (underfitting).

---

#### Step 2: Compute distance

For a new data point, compute distance to **all training samples** using a distance metric such as:

* **Euclidean distance (p = 2)**
  $$
  d(x, y) = \sqrt{\sum_{i=1}^{n}(x_i - y_i)^2}
  $$

* **Manhattan distance (p = 1)**
  $$
  d(x, y) = \sum_{i=1}^{n}|x_i - y_i|
  $$

---

#### Step 3: Identify the *k* nearest neighbors

* Sort distances in ascending order.
* Select the **k closest data points**.

---

#### Step 4: Voting / Aggregation

* **Classification**:

  * Majority voting among the k neighbors.
  * Optionally weighted by distance (closer neighbors matter more).
* **Regression**:

  * Average (or weighted average) of target values.

---

#### Step 5: Assign prediction

* The class (or value) with the highest vote (or mean) is assigned to the new data point.

---

### 4. Role of Feature Scaling

KNN is **highly sensitive to feature scale** because distance calculations dominate the algorithm.

Example:

* Feature A range: 0–1
* Feature B range: 0–10,000
  → Feature B dominates distance

**Solution**: Apply **Standardization or Normalization** before KNN.

---

### 5. Important Hyperparameters

| Hyperparameter    | Description                            |
| ----------------- | -------------------------------------- |
| `n_neighbors (k)` | Number of neighbors                    |
| `weights`         | `uniform` or `distance`                |
| `metric` / `p`    | Distance metric (Euclidean, Manhattan) |

---

### 6. Advantages of KNN

* Simple and intuitive
* No training time
* Works well with small, well-separated datasets
* Naturally handles multi-class problems

---

### 7. Disadvantages of KNN

* Computationally expensive at prediction time
* High memory usage
* Sensitive to noise and irrelevant features
* Performance degrades in high-dimensional data (curse of dimensionality)

---

### 8. Bias–Variance Trade-off in KNN

| k Value | Bias | Variance |
| ------- | ---- | -------- |
| Small k | Low  | High     |
| Large k | High | Low      |

---

### 9. KNN in Medical Context

* Good for **pattern similarity**
* Risky when:

  * Classes overlap
  * Missing critical cases (false negatives)
* Often used as a **baseline model**, not final deployment

---

### 10. One-Line Summary (Exam-Ready)

> KNN predicts the class of a new data point by measuring its distance to training samples and assigning the most frequent class among the k nearest neighbors.

---

# KNN (Code)

In [95]:
from sklearn.neighbors import KNeighborsClassifier

knn_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn",KNeighborsClassifier())
])

In [96]:
# Hyperparameter tuning 
from sklearn.model_selection import GridSearchCV

param_grid = {
    "knn__n_neighbors": [3,5,7,9,11],
    "knn__weights": ["uniform", "distance"],
    "knn__p": [1,2]
}

knn_grid = GridSearchCV(
    estimator=knn_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

### Pipeline Hyperparameter Naming (KNN / Any Model)

- When a model is inside a `Pipeline`, its hyperparameters are **nested**.
- GridSearchCV **cannot auto-detect** parameters of inner estimators.
- Hyperparameters must be referenced using:

  `step_name__parameter_name`

- Example:
  - Pipeline step: `("knn", KNeighborsClassifier())`
  - KNN hyperparameter: `n_neighbors`
  - GridSearch key: `knn__n_neighbors`

- Using `n_neighbors` alone will fail because the `Pipeline` itself has no such parameter.
- The `step_name` part depends on how you named the step:
  - If step name is `"model"` → `model__n_neighbors`

**Rule of thumb**:  
> In a Pipeline, always prefix hyperparameters with the step name followed by `__`.

In [97]:
# Encode target labels for KNN
y_train_knn = y_train.map({"benign": 0, "malignant": 1})
y_test_knn = y_test.map({"benign": 0, "malignant": 1})

### Why Encode Target Labels for KNN

- **KNN is a distance-based algorithm** that relies on optimized numeric computations.
- Internally, `KNeighborsClassifier` uses low-level routines that expect **numeric class labels**.
- Using string labels (e.g., `"benign"`, `"malignant"`) can cause failures during:
  - `predict_proba`
  - Cross-validation scoring
- Encoding labels as `0` and `1` ensures:
  - Stable distance calculations
  - Valid cross-validation scores
  - No `NaN` results or runtime warnings

**Rule**:  
> For KNN (and other distance-based models), always use numeric target labels.

In [98]:
knn_grid.fit(X_train, y_train_knn)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'knn__n_neighbors': [3, 5, 7, 9, 11], 'knn__p': [1, 2],
                         'knn__weights': ['uniform', 'distance']},
             scoring='accuracy')

In [99]:
# Best hyperparameters found by GridSearchCV
knn_grid.best_params_

{'knn__n_neighbors': 3, 'knn__p': 1, 'knn__weights': 'uniform'}

GridSearchCV selected `k=3`, Manhattan distance (`p=1`), and uniform weights, indicating strong local separability where simple nearest-neighbor voting performs best.

In [100]:

# Predict using best KNN model
y_pred_knn = knn_grid.predict(X_test)

# Accuracy
print("KNN Test accuracy:", accuracy_score(y_test_knn, y_pred_knn))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_knn, y_pred_knn))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test_knn, y_pred_knn))

KNN Test accuracy: 0.9649122807017544

Confusion Matrix:
[[72  0]
 [ 4 38]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        72
           1       1.00      0.90      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114

In [101]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

knn_accuracy = accuracy_score(y_test_knn, y_pred_knn)
knn_precision = precision_score(y_test_knn, y_pred_knn, pos_label=1)
knn_recall = recall_score(y_test_knn, y_pred_knn, pos_label=1)
knn_f1 = f1_score(y_test_knn, y_pred_knn, pos_label=1)

print("KNN Metrics")
print("Accuracy :", knn_accuracy)
print("Precision:", knn_precision)
print("Recall   :", knn_recall)
print("F1-score :", knn_f1)

KNN Metrics
Accuracy : 0.9649122807017544
Precision: 1.0
Recall   : 0.9047619047619048
F1-score : 0.95

### Logistic Regression vs KNN — Comparative Insights

**Overall performance**
- **Logistic Regression** achieved slightly higher accuracy (**97.4%**) than **KNN** (**96.5%**).
- Both models perform strongly, indicating the dataset is well-structured and separable.

**Medical relevance (malignant class)**
- **Logistic Regression**:
  - Recall (malignant) = **0.95**
  - False Negatives = **2** (missed cancers)
- **KNN**:
  - Recall (malignant) = **0.90**
  - False Negatives = **4** (missed cancers)

**Error profile**
- Logistic Regression makes fewer critical errors (lower FN), which is more important in medical diagnosis.
- KNN has **zero false positives** for benign cases but misses more malignant cases.

**Model behavior**
- Logistic Regression learns a **global linear decision boundary** and generalizes well after proper scaling.
- KNN relies on **local neighborhood similarity**, which is effective but slightly less reliable for detecting malignant cases here.

**Final insight**
- While both models are accurate, **Logistic Regression is preferable for medical use** in this dataset due to higher malignant recall and fewer missed cancer cases.

**Bottom line**
> For breast cancer classification, a well-scaled Logistic Regression provides a safer and more balanced baseline than KNN.

# Decision Tree


---

# Decision Tree — Theory (Classification)

## 1. Definition

A **Decision Tree** is a **supervised learning algorithm** that models decisions using a **tree-structured flow of conditions**, where:

* Internal nodes represent **feature-based decisions**
* Branches represent **outcomes of those decisions**
* Leaf nodes represent **final class predictions**

It belongs to the family of **non-parametric, rule-based models**.

---

## 2. Intuition

A Decision Tree works by repeatedly asking **simple yes/no (or multi-way) questions** about the data:

> “Is feature $X \leq t$?”

By chaining these questions, the model:

* Partitions the feature space
* Groups similar samples together
* Assigns a class label at the end

---

## 3. Structure of a Decision Tree

### Components

| Component     | Description                    |
| ------------- | ------------------------------ |
| Root Node     | First and most important split |
| Decision Node | Node that applies a condition  |
| Branch        | Result of a condition          |
| Leaf Node     | Final predicted class          |
| Depth         | Longest path from root to leaf |

---

## 4. How a Decision Tree is built (Training Process)

Training a Decision Tree is a **top-down, greedy, recursive process**.

### Step-by-step:

1. Start with the full dataset at the root
2. Evaluate all features and all possible split points
3. Choose the split that **best separates the classes**
4. Split the dataset into child nodes
5. Repeat the process for each child node
6. Stop when:

   * All samples belong to one class
   * Maximum depth is reached
   * Node contains too few samples

---

## 5. Split Quality (Impurity Measures)

Decision Trees aim to create **pure nodes** (nodes containing samples of only one class).

### A. Gini Impurity (default in sklearn)

$$
Gini = 1 - \sum_{i=1}^{C} p_i^2
$$

Where:

* $p_i$ = proportion of class $i$ in the node
* $C$ = number of classes

**Interpretation:**

* Gini = 0 → pure node
* Higher Gini → more mixed classes

---

### B. Entropy

$$
Entropy = - \sum_{i=1}^{C} p_i \log_2(p_i)
$$

Used with **Information Gain**:

$$
Information\ Gain = Entropy(parent) - \sum Entropy(children)
$$

**Goal:** maximize Information Gain.

---

## 6. Greedy Nature of Decision Trees

Decision Trees are **greedy algorithms**:

* They choose the **best split at the current node**
* They do **not** reconsider previous splits
* Global optimality is **not guaranteed**

This makes them:

* Fast to train
* Prone to overfitting

---

## 7. Decision Boundaries

Decision Trees create **axis-aligned, rectangular decision boundaries**.

This means:

* Each split is based on **one feature at a time**
* Boundaries are not smooth or linear
* They can model complex non-linear patterns

---

## 8. Overfitting in Decision Trees

A fully grown tree:

* Memorizes training data
* Has very high variance
* Performs poorly on unseen data

### Symptoms:

* Training accuracy ≈ 100%
* Test accuracy significantly lower

---

## 9. Controlling Overfitting (Regularization)

| Hyperparameter      | Effect                                  |
| ------------------- | --------------------------------------- |
| `max_depth`         | Limits tree height                      |
| `min_samples_split` | Minimum samples to split a node         |
| `min_samples_leaf`  | Minimum samples at a leaf               |
| `max_features`      | Number of features considered per split |
| `ccp_alpha`         | Cost-complexity pruning                 |

---

## 10. Advantages

* No feature scaling required
* Handles non-linear relationships
* Works with numerical & categorical data
* Interpretable and explainable
* Handles outliers well

---

## 11. Disadvantages

* High variance (unstable)
* Sensitive to small data changes
* Poor extrapolation
* Bias toward features with many split points

---

## 12. Decision Tree vs Other Models

| Model               | Key Difference               |
| ------------------- | ---------------------------- |
| Logistic Regression | Linear, parametric           |
| KNN                 | Distance-based, lazy learner |
| Decision Tree       | Rule-based, greedy           |
| Random Forest       | Ensemble of trees            |

---

## 13. When to use Decision Trees

* Interpretability is important
* Data has non-linear patterns
* No time for feature scaling
* Mixed data types

---

## 14. One-line exam summary

> A Decision Tree is a non-parametric supervised learning algorithm that recursively splits the data using feature-based conditions to minimize impurity and produce interpretable decision rules.

---

# Decision Tree (Code)

In [102]:
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [103]:
data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = pd.Series(data.target).map(
    {0:data.target_names[0], 1:data.target_names[1]}
)
df.head()

   mean radius  mean texture  ...  worst fractal dimension     target
0        17.99         10.38  ...                  0.11890  malignant
1        20.57         17.77  ...                  0.08902  malignant
2        19.69         21.25  ...                  0.08758  malignant
3        11.42         20.38  ...                  0.17300  malignant
4        20.29         14.34  ...                  0.07678  malignant

[5 rows x 31 columns]

In [104]:
data.target_names[0]

np.str_('malignant')

In [105]:
X = df.drop(columns=["target"])
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [106]:
dt_pipeline = Pipeline(steps=[
    ("decision_tree", DecisionTreeClassifier(random_state=42))
])

In [107]:
param_grid = {
    "decision_tree__criterion": ["gini", "entropy"],
    "decision_tree__max_depth": [None, 3, 5, 7, 10],
    "decision_tree__min_samples_split": [2, 5, 10, 20],
    "decision_tree__min_samples_leaf": [1, 2, 5, 10]
}

In [108]:
# GridSearch with cross-validation
dt_grid = GridSearchCV(
    estimator=dt_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [109]:
dt_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('decision_tree',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'decision_tree__criterion': ['gini', 'entropy'],
                         'decision_tree__max_depth': [None, 3, 5, 7, 10],
                         'decision_tree__min_samples_leaf': [1, 2, 5, 10],
                         'decision_tree__min_samples_split': [2, 5, 10, 20]},
             scoring='accuracy')

In [110]:
# Best hyperparameters found by GridSearchCV
dt_grid.best_params_

{'decision_tree__criterion': 'entropy',
 'decision_tree__max_depth': None,
 'decision_tree__min_samples_leaf': 2,
 'decision_tree__min_samples_split': 5}

In [111]:
# Extract the best Decision Tree model from the pipeline
best_dt = dt_grid.best_estimator_

"""or just 
y_pred_dt = dt_grid.predict(X_test)
both works
    """
# Predictions on test data
y_pred_dt = best_dt.predict(X_test)

In [112]:

# Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Decision Test accuracy:", accuracy_score(y_test, y_pred_dt))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

Decision Test accuracy: 0.956140350877193

Confusion Matrix:
[[72  0]
 [ 5 37]]

Classification Report:
              precision    recall  f1-score   support

      benign       0.94      1.00      0.97        72
   malignant       1.00      0.88      0.94        42

    accuracy                           0.96       114
   macro avg       0.97      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114

In [113]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

dt_accuracy_acc = accuracy_score(y_test, y_pred_dt)
dt_precision_acc = precision_score(y_test, y_pred_dt, pos_label="malignant")
dt_recall_acc = recall_score(y_test, y_pred_dt, pos_label="malignant")
dt_f1_acc = f1_score(y_test, y_pred_dt, pos_label="malignant")

print("Decision Tree (Accuracy-Optimized / Default) Metrics")
print("Accuracy :", dt_accuracy_acc)
print("Precision:", dt_precision_acc)
print("Recall   :", dt_recall_acc)
print("F1-score :", dt_f1_acc)

Decision Tree (Accuracy-Optimized / Default) Metrics
Accuracy : 0.956140350877193
Precision: 1.0
Recall   : 0.8809523809523809
F1-score : 0.9367088607594937

## Decision Tree — Model Insight

The tuned Decision Tree achieved a **test accuracy of ~95.6%**, which indicates solid overall performance but slightly underperforms compared to Logistic Regression and is on par with KNN.

### Strengths
- **Perfect recall for benign cases (1.00)**: the model does not incorrectly flag healthy patients as cancerous.
- **High precision for malignant cases (1.00)**: when the model predicts cancer, it is always correct.
- **Interpretability**: decision paths can be easily visualized and explained, making the model transparent.

### Limitations (critical in medical context)
- **Lower recall for malignant cases (0.88)**: the model misses **5 cancer cases**, which is higher than:
  - Logistic Regression (2 missed cases)
  - KNN (4 missed cases)
- This indicates a **conservative decision boundary**, likely caused by pruning (`min_samples_leaf`, `min_samples_split`) to control overfitting.

### Comparative perspective
- Compared to **Logistic Regression**, the Decision Tree sacrifices malignant recall for interpretability.
- Compared to **KNN**, it produces slightly more false negatives, making it less suitable for safety-critical diagnosis on its own.

### Final takeaway
> A single Decision Tree is **useful for explanation and rule discovery**, but for medical diagnosis where missing malignant cases is costly, it is **better used as a base learner** in ensemble methods such as **Random Forests or Gradient Boosting**.

##  Decision tree with recall

In [114]:
# Decision Tree pipeline (recall-focused)
dt_recall_pipeline = Pipeline(steps=[
    ("decision_tree", DecisionTreeClassifier(
        random_state=42,
        class_weight={"malignant":2, "benign":1}
    ))
])

In [115]:
# Hyperparameter grid (slightly less aggressive pruning)
param_grid = {
    "decision_tree__max_depth": [None, 5, 7, 10],
    "decision_tree__min_samples_split": [2, 5, 10],
    "decision_tree__min_samples_leaf": [1, 2, 5],
    "decision_tree__criterion": ["gini", "entropy"]
}

In [116]:
# GridSearch optimized for recall
dt_recall_grid = GridSearchCV(
    estimator=dt_recall_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="recall_weighted",
    n_jobs=-1
)

In [117]:
# Fit recall-optimized Decision Tree with cross-validation
dt_recall_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('decision_tree',
                                        DecisionTreeClassifier(class_weight={'benign': 1,
                                                                             'malignant': 2},
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'decision_tree__criterion': ['gini', 'entropy'],
                         'decision_tree__max_depth': [None, 5, 7, 10],
                         'decision_tree__min_samples_leaf': [1, 2, 5],
                         'decision_tree__min_samples_split': [2, 5, 10]},
             scoring='recall_weighted')

In [118]:
# Best hyperparameters selected when optimizing recall
dt_recall_grid.best_params_

{'decision_tree__criterion': 'gini',
 'decision_tree__max_depth': 5,
 'decision_tree__min_samples_leaf': 2,
 'decision_tree__min_samples_split': 2}

In [119]:
# Extract best recall-optimized tree
best_dt_recall = dt_recall_grid.best_estimator_

# Predictions on test set
y_pred_dt_recall = best_dt_recall.predict(X_test)

In [120]:
print("Test accuracy:", accuracy_score(y_test, y_pred_dt_recall))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt_recall))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt_recall))

Test accuracy: 0.9122807017543859

Confusion Matrix:
[[69  3]
 [ 7 35]]

Classification Report:
              precision    recall  f1-score   support

      benign       0.91      0.96      0.93        72
   malignant       0.92      0.83      0.88        42

    accuracy                           0.91       114
   macro avg       0.91      0.90      0.90       114
weighted avg       0.91      0.91      0.91       114

In [121]:
y_pred_dt_recall_optimized = y_pred_dt_recall
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

dt_recall_opt_accuracy = accuracy_score(y_test, y_pred_dt_recall_optimized)
dt_recall_opt_precision = precision_score(
    y_test, y_pred_dt_recall_optimized, pos_label="malignant"
)
dt_recall_opt_recall = recall_score(
    y_test, y_pred_dt_recall_optimized, pos_label="malignant"
)
dt_recall_opt_f1 = f1_score(
    y_test, y_pred_dt_recall_optimized, pos_label="malignant"
)

print("Decision Tree (Recall-Optimized) Metrics")
print("Accuracy :", dt_recall_opt_accuracy)
print("Precision:", dt_recall_opt_precision)
print("Recall   :", dt_recall_opt_recall)
print("F1-score :", dt_recall_opt_f1)

Decision Tree (Recall-Optimized) Metrics
Accuracy : 0.9122807017543859
Precision: 0.9210526315789473
Recall   : 0.8333333333333334
F1-score : 0.875

### Insight: Recall-Optimized Decision Tree

Optimizing a single Decision Tree for recall reduced overall performance and **did not improve malignant detection**. Test accuracy dropped to **91.2%**, malignant recall decreased to **0.83**, and **false negatives increased to 7**, making the model less suitable for medical diagnosis. This happens because Decision Trees are **greedy and high-variance**; forcing recall disrupts optimal splits and harms generalization. The result confirms that **standalone Decision Trees are limited for recall-critical tasks** and are better used as base learners in ensemble models like **Random Forests**.

# Random Forest

Random Forest trains decision trees in parallel because each tree is built independently, unlike boosting methods which require sequential training.

![Image](https://miro.medium.com/1%2Ai0o8mjFfCn-uD79-F1Cqkw.png)

![Image](https://media.geeksforgeeks.org/wp-content/uploads/20250627112439534287/Random-forest-algorithm.webp)

![Image](https://miro.medium.com/1%2AjE1Cb1Dc_p9WEOPMkC95WQ.png)

## Random Forest — Textbook-Style Note

### Definition

**Random Forest** is a supervised **ensemble learning** algorithm that constructs a large number of decision trees during training and combines their outputs to produce a final prediction. For **classification**, the final output is determined by **majority voting**, while for **regression**, it is obtained by **averaging** the predictions of all trees. The core idea is that a collection of diverse, weak learners can collectively form a strong and robust model.

---

### Working Principle of Random Forest

1. **Bootstrap Sampling (Bagging)**
   Each decision tree is trained on a randomly selected subset of the training data (sampling with replacement). As a result, every tree sees a slightly different dataset.

2. **Random Feature Selection**
   At each split in a tree, only a random subset of features is considered rather than all available features. This introduces diversity among trees and reduces correlation between them.

3. **Independent Tree Construction**
   Each tree is grown independently and usually to a large depth (often without pruning), allowing it to learn complex patterns.

4. **Prediction Aggregation**

   * **Classification**: The class predicted by the majority of trees is selected.
   * **Regression**: The final prediction is the mean of predictions from all trees.

---

### Why Random Forest Works Well

* Random sampling of **data** and **features** ensures that trees are diverse.
* Errors made by individual trees tend to cancel out when aggregated.
* This significantly **reduces overfitting**, a common issue in single decision trees.
* The ensemble approach improves **generalization performance** on unseen data.

---

### Key Characteristics

* **Robustness to Noise**: Random Forest performs well even when the dataset contains noise or irrelevant features.
* **Feature Importance Estimation**: It provides a measure of how important each feature is in making predictions.
* **Non-parametric Nature**: No assumptions are made about the underlying data distribution.
* **Versatility**: Applicable to both classification and regression problems.
* **Scalability**: Can handle large datasets with high dimensionality.

---

### Assumptions of Random Forest

* Individual decision trees are **weak learners** but better than random guessing.
* Diversity among trees improves the overall predictive performance.
* A sufficiently large and representative dataset is available so that different trees learn varied patterns.

---

### Applications

* **Classification**: Spam detection, disease diagnosis, fraud detection, sentiment analysis.
* **Regression**: House price prediction, demand forecasting, risk estimation.

---

### Advantages

* High accuracy and strong generalization capability.
* Resistant to overfitting compared to single decision trees.
* Works well with both numerical and categorical data.
* Does not require feature scaling or normalization.

---

### Limitations

* Computationally expensive in terms of training time and memory, especially with many trees.
* Less interpretable than simple models such as linear regression or a single decision tree.
* Large forests can be slow during inference in real-time systems.

---

### Summary

Random Forest is a powerful ensemble technique that leverages randomness and aggregation to achieve high accuracy and robustness. By combining multiple diverse decision trees, it mitigates individual model weaknesses and provides reliable performance across a wide range of real-world machine learning tasks.

# Random Forest (Code)

In [122]:
from sklearn.ensemble import RandomForestClassifier

Why scaling is unnecessary here

- Random Forest is tree-based.
- Decision trees split data using feature thresholds, not distances or gradients.
- Scaling does not change the order of values, so splits remain identical.
- Adding StandardScaler only adds overhead and no performance benefit

When scaling is required (contrast)

- Logistic Regression
- SVM
- KNN
- Neural Networks

In [123]:

rf_pipeline = Pipeline(steps=[
    ("random_forest", RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ))
])

In [124]:
rf_param_grid ={
    "random_forest__n_estimators":[100,200,300],
    "random_forest__max_depth":[None,5,10,20],
    "random_forest__min_samples_split":[2,5,10],
    "random_forest__min_samples_leaf":[1,2,4],
    "random_forest__max_features":["sqrt", "log2"]
}

## Random Forest Hyperparameters — Concise Intuition

### `n_estimators` (number of trees)
- Typical values: **100, 200, 300**
- More trees → more stable predictions
- Gains plateau after a point; 100 is a strong default

---

### `max_depth` (tree depth)
- Values: **None, 5, 10, 20**
- Controls model complexity
- Shallow → underfitting, very deep → overfitting

---

### `min_samples_split`
- Values: **2, 5, 10**
- Minimum samples needed to split a node
- Higher values reduce noise and overfitting

---

### `min_samples_leaf`
- Values: **1, 2, 4**
- Minimum samples in a leaf
- Larger values improve generalization

---

### `max_features`
- `"sqrt"` → √(number of features)  
- `"log2"` → log₂(number of features)
- Forces trees to be different → better ensemble performance

---

### One-line takeaway
> These values are chosen to balance **bias vs variance**, **tree diversity**, and **compute cost**, based on Random Forest theory and practice.

`max_features` controls how many features a decision tree is allowed to consider **at each split**. Instead of evaluating all available features, Random Forest deliberately restricts the choice to a small random subset (such as √N or log₂N features). This is critical because it **forces different trees to make splits based on different features**, even when some features are very strong predictors. If all trees always see all features, they tend to select the same dominant features at the top splits, making the trees highly similar (correlated). By limiting `max_features`, Random Forest increases **tree diversity**, reduces correlation among trees, and allows the ensemble’s averaging process to cancel out individual tree errors. This diversity is a key reason Random Forest achieves better generalization and lower variance than a collection of similar trees.

In [125]:
rf_grid = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=rf_param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

In [126]:
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('random_forest',
                                        RandomForestClassifier(n_jobs=-1,
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'random_forest__max_depth': [None, 5, 10, 20],
                         'random_forest__max_features': ['sqrt', 'log2'],
                         'random_forest__min_samples_leaf': [1, 2, 4],
                         'random_forest__min_samples_split': [2, 5, 10],
                         'random_forest__n_estimators': [100, 200, 300]},
             scoring='accuracy', verbose=1)

In [127]:
# Best model from GridSearch
best_rf = rf_grid.best_estimator_

# Predictions on test set
y_pred_rf = best_rf.predict(X_test)

# Best hyperparameters
print("Best Hyperparameters:")
print(rf_grid.best_params_)

# Accuracy
print("\nRandom Forest Test accuracy:", accuracy_score(y_test, y_pred_rf))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Best Hyperparameters:
{'random_forest__max_depth': None, 'random_forest__max_features': 'sqrt', 'random_forest__min_samples_leaf': 1, 'random_forest__min_samples_split': 2, 'random_forest__n_estimators': 100}

Random Forest Test accuracy: 0.9736842105263158

Confusion Matrix:
[[72  0]
 [ 3 39]]

Classification Report:
              precision    recall  f1-score   support

      benign       0.96      1.00      0.98        72
   malignant       1.00      0.93      0.96        42

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

In [128]:
from sklearn.metrics import precision_score, recall_score, f1_score

rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_precision = precision_score(y_test, y_pred_rf, pos_label="malignant")
rf_recall = recall_score(y_test, y_pred_rf, pos_label="malignant")
rf_f1 = f1_score(y_test, y_pred_rf, pos_label="malignant")

print("Random Forest Metrics")
print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1-score :", rf_f1)

Random Forest Metrics
Accuracy : 0.9736842105263158
Precision: 1.0
Recall   : 0.9285714285714286
F1-score : 0.9629629629629629

### Random Forest vs Logistic Regression vs KNN — Comparative Insights

#### Overall performance
- **Random Forest** achieved the **highest accuracy (97.4%)**, outperforming both **Logistic Regression (97.4%)** and **KNN (96.5%)** by a small but meaningful margin.
- All three models perform strongly, indicating the dataset is well-behaved and highly predictive.

#### Medical relevance (malignant class is critical)
- **Random Forest**
  - Recall (malignant) = **0.93**
  - False Negatives = **3**
- **Logistic Regression**
  - Recall (malignant) ≈ **0.95**
  - False Negatives = **2**
- **KNN**
  - Recall (malignant) = **0.90**
  - False Negatives = **4**

> In medical diagnosis, **false negatives are the most dangerous errors**. Logistic Regression performs best here, followed closely by Random Forest.

#### Error profile
- **Random Forest** shows a strong balance:
  - **Zero false positives** for benign cases
  - Slightly more false negatives than Logistic Regression
- **Logistic Regression** minimizes missed cancer cases.
- **KNN** misses the most malignant cases, making it less reliable in this context.

#### Model behavior
- **Random Forest**
  - Captures **non-linear feature interactions**
  - Robust to noise and feature correlations
  - Less interpretable
- **Logistic Regression**
  - Learns a **global linear decision boundary**
  - Highly interpretable and stable
  - Strong baseline for clinical settings
- **KNN**
  - Relies on **local neighborhood similarity**
  - Sensitive to noise and data distribution
  - Requires careful scaling and tuning of *k*

#### Final insight
- **Best overall accuracy**: Random Forest  
- **Safest medical choice (lowest FN)**: Logistic Regression  
- **Least reliable for malignant detection**: KNN  

#### Bottom line
> For breast cancer classification, **Logistic Regression remains the safest clinical baseline**, while **Random Forest provides the best overall predictive power**. KNN, although competitive, is less suitable due to higher missed malignant cases.

# Support Vector Machine

## Support Vector Machine (SVM)

### What is a Support Vector Machine?
A **Support Vector Machine (SVM)** is a supervised machine learning algorithm used for **classification and regression** tasks. Its core objective is to find an **optimal decision boundary (hyperplane)** that separates data points of different classes with the **maximum possible margin**.

The data points that lie closest to the decision boundary are called **support vectors**. These points are critical because they entirely define the position and orientation of the hyperplane.

---

### Why is SVM Used?
SVM is widely used because of the following strengths:

- **Maximum Margin Principle**:  
  By maximizing the margin between classes, SVM improves generalization and reduces the risk of overfitting.

- **Effective in High-Dimensional Spaces**:  
  SVM performs well when the number of features is large, even if the number of samples is limited.

- **Robust to Overfitting**:  
  Especially effective when there is a clear margin of separation between classes.

- **Kernel Trick**:  
  SVM can handle **non-linearly separable data** by implicitly mapping data into higher-dimensional spaces using kernels (e.g., linear, polynomial, RBF).

---

### Soft Margin and Misclassification
In real-world data, perfect separation is often impossible. SVM addresses this using a **soft margin**, which allows some misclassifications while still maximizing the margin.

- The **regularization parameter (C)** controls this trade-off:
  - Large `C`: Penalizes misclassification heavily → narrower margin, lower bias, higher variance.
  - Small `C`: Allows more misclassification → wider margin, higher bias, lower variance.

---

### Role of Cross-Validation in SVM
**Cross-validation** is used to determine the **best soft margin (optimal C value)**.

- The dataset is split into multiple folds.
- For different values of `C`, the model is trained and evaluated.
- Cross-validation estimates **how many misclassifications occur on unseen data**.
- The value of `C` that results in **minimum validation error** (best balance between margin size and misclassification) is selected.

This ensures the SVM model generalizes well rather than fitting noise in the training data.

---

### Summary
- SVM finds a decision boundary with maximum margin.
- Support vectors define the model.
- Soft margin allows controlled misclassification.
- Cross-validation selects the best margin by evaluating misclassification across folds.

## Hard Margin in Support Vector Machine (SVM)

### What is Hard Margin?
A **hard margin SVM** is a type of SVM where the model **does not allow any misclassification**. It finds a decision boundary that **perfectly separates** the classes while maximizing the margin.

### Key Characteristics
- **Zero tolerance for misclassification**
- Assumes data is **perfectly linearly separable**
- All data points must lie **outside the margin**
- No slack variables are allowed

### Limitations
- Very **sensitive to noise and outliers**
- Rarely practical for real-world data
- Fails when classes overlap

Because of these limitations, hard margin SVM is mostly used for **theoretical understanding**, not real datasets.

---

## Kernel in Support Vector Machine (SVM)

### What is a Kernel?
A **kernel** is a mathematical function that allows SVM to **separate non-linearly separable data** by implicitly mapping it into a **higher-dimensional feature space** where linear separation becomes possible.

This avoids explicitly computing the transformation, making SVM computationally efficient.

This concept is known as the **Kernel Trick**.

---

### Why Kernels are Needed
- Real-world data is often **non-linear**
- Linear decision boundaries are insufficient
- Kernels enable **complex decision boundaries** without high computational cost

---

### Common Types of Kernels

- **Linear Kernel**  
  Used when data is approximately linearly separable.

- **Polynomial Kernel**  
  Models interactions between features.

- **Radial Basis Function (RBF / Gaussian) Kernel**  
  Most commonly used; effective for complex, non-linear patterns.

- **Sigmoid Kernel**  
  Inspired by neural networks (less commonly used).

---

### Summary
- **Hard margin**: No misclassification allowed; works only for perfectly separable data.
- **Kernel**: A function that enables SVM to handle non-linear data by transforming it into a higher-dimensional space.
- **Kernel trick**: Performs this transformation implicitly and efficiently.

![soft margin vs hard margin](../data/images/soft_margin_vs_hard_margin.png)

## Choosing Between Hard Margin and Soft Margin in SVM

### Is the Choice Automatic?
- **Hard margin is NOT chosen automatically**
- **Soft margin is the default and practical choice**
- The **degree of softness** is controlled by the hyperparameter **C**, which is selected using **cross-validation**

---

### Hard Margin SVM
- Requires **perfectly separable data**
- **No misclassification allowed**
- Extremely sensitive to noise and outliers
- Rarely used in real-world applications

> Hard margin is equivalent to using a **very large C**, which is generally avoided.

---

### Soft Margin SVM
- Allows **some misclassification**
- Handles noisy and overlapping data
- Controlled by regularization parameter **C**
- **C is tuned automatically via cross-validation**

---

### What Happens in Practice?
1. Soft margin SVM is used by default
2. A range of `C` values is defined
3. Cross-validation evaluates misclassification on validation sets
4. The `C` with best generalization performance is selected

---

### Final Conclusion
- **Hard margin** → Theoretical, rarely used  
- **Soft margin** → Default, practical choice  
- **C parameter** → Automatically optimized using cross-validation

# SVM (Code)

In [129]:
from sklearn.svm import SVC

In [130]:
svm_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("svm", SVC())
])

In [131]:
param_grid = {
    "svm__kernel": ["linear", "rbf"],
    "svm__C": [0.01, 0.1, 10, 100],
    "svm__gamma":["scale", 0.01, 0.1,1]
}

## SVM Hyperparameters: C and Gamma (Quick Recall)

### What is C?
**C controls how strictly SVM penalizes misclassification.**

- Small C → wider margin, more errors allowed (underfitting)
- Large C → narrow margin, fewer errors allowed (overfitting)

**Why we search C logarithmically**
- ❌ 0.1 → 0.2 → 0.3 → little behavioral change
- ✅ 0.1 → 1 → 10 → explores different model regimes

**Example**
- C = 0.1 → ignores some errors, smooth boundary
- C = 10 → tries to classify almost everything correctly

---

### What is Gamma?
**Gamma controls how far a single data point influences the decision boundary** (RBF kernel).

- Small gamma → smooth, global boundary (underfitting)
- Large gamma → complex, local boundary (overfitting)

**Why we search gamma logarithmically**
- ❌ 0.05 → 0.1 → minor shape change
- ✅ 0.01 → 0.1 → 1 → captures underfit → overfit behavior

**Example**
- gamma = 0.01 → very smooth boundary
- gamma = 1 → boundary tightly wraps around points

---

### Key Rule (Remember This)
> **C controls error tolerance, gamma controls boundary complexity — both must be tuned across orders of magnitude, not small linear steps.**

### What is `gamma="scale"` in SVM?

`gamma="scale"` automatically sets gamma based on the data:

$$
\gamma = \frac{1}{(\text{number of features}) \times \text{variance of } X}
$$

**Why it is used**
- Adapts to feature scale
- Prevents extreme overfitting or underfitting
- Recommended default in scikit-learn

**In short**
> `gamma="scale"` is a safe, data-dependent default that adjusts gamma automatically instead of fixing it manually.

In [132]:
svm_grid = GridSearchCV(
    estimator=svm_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
svm_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC())]),
             n_jobs=-1,
             param_grid={'svm__C': [0.01, 0.1, 10, 100],
                         'svm__gamma': ['scale', 0.01, 0.1, 1],
                         'svm__kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [133]:
best_svm = svm_grid.best_estimator_
svm_y_pred = best_svm.predict(X_test)

In [134]:
svm_best_params = svm_grid.best_params_
print("Best hyperparameters:", svm_best_params)

svm_accuracy = accuracy_score(y_test, svm_y_pred)
print("Test accuracy:", svm_accuracy)

svm_confusion = confusion_matrix(y_test, svm_y_pred)
print("\nConfusion Matrix:\n", svm_confusion)

svm_report = classification_report(y_test, svm_y_pred)
print("\nClassification Report:\n", svm_report)

Best hyperparameters: {'svm__C': 10, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}
Test accuracy: 0.9736842105263158

Confusion Matrix:
 [[72  0]
 [ 3 39]]

Classification Report:
               precision    recall  f1-score   support

      benign       0.96      1.00      0.98        72
   malignant       1.00      0.93      0.96        42

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

In [135]:
from sklearn.metrics import precision_score, recall_score, f1_score

svm_precision = precision_score(y_test, svm_y_pred, pos_label="malignant")
svm_recall = recall_score(y_test, svm_y_pred, pos_label="malignant")
svm_f1 = f1_score(y_test, svm_y_pred, pos_label="malignant")

print("SVM Metrics")
print("Accuracy :", svm_accuracy)
print("Precision:", svm_precision)
print("Recall   :", svm_recall)
print("F1-score :", svm_f1)

SVM Metrics
Accuracy : 0.9736842105263158
Precision: 1.0
Recall   : 0.9285714285714286
F1-score : 0.9629629629629629

# Naive Bayes

## Naive Bayes Classifier

### What is Naive Bayes?
**Naive Bayes** is a supervised, probabilistic classification algorithm based on **Bayes’ Theorem**.  
It is called *naive* because it assumes that all features are **conditionally independent** given the class label.

Despite this strong assumption, Naive Bayes performs very well in many real-world problems.

---

### When is Naive Bayes Used?
Naive Bayes is commonly used when:

- The dataset is **high-dimensional**
- Features are **independent or weakly correlated**
- Fast training and prediction are required
- Probabilistic interpretation is useful

Typical applications:
- Text classification (spam detection, sentiment analysis)
- Medical diagnosis
- Document categorization

---

### How Does Naive Bayes Work?

Naive Bayes applies **Bayes’ Theorem**:

$$
P(y \mid X) = \frac{P(X \mid y) \, P(y)}{P(X)}
$$

Where:
- $(y \mid X)$ → Posterior probability (class given features)
- $P(X \mid y)$ → Likelihood (features given class)
- $P(y)$ → Prior probability of the class
- $P(X)$ → Evidence (constant for all classes)

---

### Naive Independence Assumption
Naive Bayes assumes:

$$
P(X \mid y) = P(x_1 \mid y)\, P(x_2 \mid y)\, \cdots\, P(x_n \mid y)
$$
This simplifies computation and enables scalability.

---

### Classification Rule
For each class:
1. Compute the posterior probability
2. Choose the class with **maximum posterior probability**

$$
\hat{y} = \arg\max_y \; P(y)\prod_i P(x_i \mid y)
$$

---

### Why It Works Well
- Works well even when independence assumption is violated
- Requires small amount of training data
- Robust to irrelevant features
- Computationally efficient

---

### Summary
- Naive Bayes is a **probabilistic classifier**
- Based on **Bayes’ Theorem**
- Assumes **feature independence**
- Fast, simple, and effective for high-dimensional data

---
--- 
---
Naive Bayes assumes feature independence, but in the breast cancer dataset:

- Many features are strongly correlated

    - e.g., radius, perimeter, area, concavity

- This violates the core assumption of Naive Bayes

# Naive Bayes code

In [136]:
from sklearn.naive_bayes import GaussianNB

Why GaussianNB

- Breast cancer features are continuous

- Assumes each feature follows a normal distribution

- No scaling required (but allowed)

In [137]:
print(X_train.var().describe())

count        30.000000
mean      15774.861940
std       65501.628850
min           0.000007
25%           0.000385
50%           0.005571
75%          17.009732
max      339127.074426
dtype: float64

## Variance Insight for Choosing `var_smoothing` (Gaussian Naive Bayes)

### Observed Feature Variance (Training Data)
- **Minimum variance** ≈ `7 × 10⁻⁶`
- **Median variance** ≈ `5 × 10⁻³`
- **Maximum variance** ≈ `3.39 × 10⁵`
- Variance spans **many orders of magnitude**

---

### What This Means
- Some features have **extremely small variance** → risk of numerical instability
- Some features have **very large variance** → smoothing must not dominate them
- A single fixed variance assumption would be unsafe without smoothing

---

### Implication for `var_smoothing`
- `var_smoothing` must be:
  - **Larger than near-zero variance** (`~10⁻⁶`)
  - **Much smaller than typical variance** (`~10⁻³` and above)

---

### Justified Hyperparameter Range
```text
10⁻¹²  → tests almost no smoothing
10⁻¹⁰
10⁻⁹
10⁻⁸
10⁻⁷   → safely stabilizes smallest-variance features

`var_smoothing` must be much smaller than the smallest feature variance, which is why values like 10⁻¹² to 10⁻⁷ are correct, not 10⁻⁶ to 10⁻³.

In [138]:

nb_pipeline = Pipeline(steps=[
    ("nb", GaussianNB())
])

param_grid = {
    "nb__var_smoothing": np.logspace(-12,-7,num=6)
}

In [139]:
nb_grid = GridSearchCV(
    estimator=nb_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
nb_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Pipeline(steps=[('nb', GaussianNB())]), n_jobs=-1,
             param_grid={'nb__var_smoothing': array([1.e-12, 1.e-11, 1.e-10, 1.e-09, 1.e-08, 1.e-07])},
             scoring='accuracy')

In [140]:
best_nb = nb_grid.best_estimator_
nb_y_pred = best_nb.predict(X_test)

In [141]:
print("Best var_smoothing:", nb_grid.best_params_)
nb_accuracy = accuracy_score(y_test, nb_y_pred)
print("Test accuracy:", nb_accuracy)
nb_confusion = confusion_matrix(y_test, nb_y_pred)
print("\nConfusion Matrix:\n", nb_confusion)
nb_report = classification_report(y_test, nb_y_pred)
print("\nClassification Report:\n", nb_report)

Best var_smoothing: {'nb__var_smoothing': np.float64(1e-09)}
Test accuracy: 0.9385964912280702

Confusion Matrix:
 [[72  0]
 [ 7 35]]

Classification Report:
               precision    recall  f1-score   support

      benign       0.91      1.00      0.95        72
   malignant       1.00      0.83      0.91        42

    accuracy                           0.94       114
   macro avg       0.96      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114

In [142]:
from sklearn.metrics import precision_score, recall_score, f1_score

nb_precision = precision_score(y_test, nb_y_pred, pos_label="malignant")
nb_recall = recall_score(y_test, nb_y_pred, pos_label="malignant")
nb_f1 = f1_score(y_test, nb_y_pred, pos_label="malignant")

print("Naive Bayes Metrics")
print("Accuracy :", nb_accuracy)
print("Precision:", nb_precision)
print("Recall   :", nb_recall)
print("F1-score :", nb_f1)

Naive Bayes Metrics
Accuracy : 0.9385964912280702
Precision: 1.0
Recall   : 0.8333333333333334
F1-score : 0.9090909090909091

# Compare Models

In [143]:
import pandas as pd

results = pd.DataFrame([
    ["Logistic Regression", log_accuracy, log_precision, log_recall, log_f1],
    ["KNN", knn_accuracy, knn_precision, knn_recall, knn_f1],
    ["Decision Tree (Accuracy)", dt_accuracy_acc, dt_precision_acc, dt_recall_acc, dt_f1_acc],
    ["Decision Tree (Recall)", dt_recall_opt_accuracy, dt_recall_opt_precision, dt_recall_opt_recall, dt_recall_opt_f1],
    ["Random Forest", rf_accuracy, rf_precision, rf_recall, rf_f1],
    ["SVM", svm_accuracy, svm_precision, svm_recall, svm_f1],
    ["Naive Bayes", nb_accuracy, nb_precision, nb_recall, nb_f1],
], columns=["Model", "Accuracy", "Precision", "Recall", "F1"])

results

                      Model  Accuracy  Precision    Recall        F1
0       Logistic Regression  0.973684   0.975610  0.952381  0.963855
1                       KNN  0.964912   1.000000  0.904762  0.950000
2  Decision Tree (Accuracy)  0.956140   1.000000  0.880952  0.936709
3    Decision Tree (Recall)  0.912281   0.921053  0.833333  0.875000
4             Random Forest  0.973684   1.000000  0.928571  0.962963
5                       SVM  0.973684   1.000000  0.928571  0.962963
6               Naive Bayes  0.938596   1.000000  0.833333  0.909091

In [144]:
ranked_results = results.sort_values(
    by=["Recall", "F1", "Accuracy"],
    ascending=False
).reset_index(drop=True)

ranked_results

                      Model  Accuracy  Precision    Recall        F1
0       Logistic Regression  0.973684   0.975610  0.952381  0.963855
1             Random Forest  0.973684   1.000000  0.928571  0.962963
2                       SVM  0.973684   1.000000  0.928571  0.962963
3                       KNN  0.964912   1.000000  0.904762  0.950000
4  Decision Tree (Accuracy)  0.956140   1.000000  0.880952  0.936709
5               Naive Bayes  0.938596   1.000000  0.833333  0.909091
6    Decision Tree (Recall)  0.912281   0.921053  0.833333  0.875000

### Why Models Are Ranked by Recall → F1 → Accuracy (Breast Cancer)

- **Recall (malignant) is prioritized** because false negatives mean missing cancer cases, which is clinically dangerous.
- **F1-score comes next** to ensure high recall is not achieved at the cost of too many false positives.
- **Accuracy is last** because class imbalance can make a model look good even if it misses malignant cases.

> In medical diagnosis, minimizing false negatives is more important than maximizing overall accuracy.

In [145]:
best_model = ranked_results.iloc[0]
print("Best Model for Breast Cancer Classification:")
print(best_model)

Best Model for Breast Cancer Classification:
Model        Logistic Regression
Accuracy                0.973684
Precision                0.97561
Recall                  0.952381
F1                      0.963855
Name: 0, dtype: object

### Final Model Selection

All classification models were evaluated using accuracy, precision, recall, and F1-score, with **recall for the malignant class** prioritized due to medical risk.

**Logistic Regression** emerged as the best-performing model, achieving:
- High malignant recall (0.95)
- Strong precision (0.98)
- Best overall F1-score

This indicates that a well-regularized linear model is sufficient for the Breast Cancer dataset and offers both strong performance and interpretability.