# Normalization vs Standardization

### Normalization
Normalization rescales numerical features to a fixed range, most commonly **[0, 1]** (and in some cases **[-1, 1]**). It is used to bring all features onto the same scale when their original magnitudes differ significantly. Normalization preserves relative distances between values but is sensitive to outliers, since the minimum and maximum values determine the scaling range. It is commonly applied in distance-based algorithms and models that require bounded inputs.

### Standardization
Standardization transforms numerical features so that they have a **mean of 0** and a **standard deviation of 1**. Unlike normalization, it does not bound the values to a specific range and instead rescales data based on its statistical properties. Standardization preserves the shape of the original data distribution and is particularly suitable when features are approximately Gaussian or when using gradient-based and linear models.

## Normalization(Min-Max Scaling)

In [112]:
import seaborn as sns
import pandas as pd 

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [114]:
num_df = df[["total_bill", "size"]]
num_df.describe()

       total_bill        size
count  244.000000  244.000000
mean    19.785943    2.569672
std      8.902412    0.951100
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.000000
75%     24.127500    3.000000
max     50.810000    6.000000

In [115]:
from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler
minmax_scaler = MinMaxScaler()

# Apply normalization
normalized_array = minmax_scaler.fit_transform(num_df)

# Convert back to DataFrame for readability
normalized_df = pd.DataFrame(
    normalized_array,
    columns=num_df.columns
)

# Inspect normalized values
normalized_df.head()

   total_bill  size
0    0.291579   0.2
1    0.152283   0.4
2    0.375786   0.4
3    0.431713   0.2
4    0.450775   0.6

In [116]:
print(normalized_df.describe())

       total_bill        size
count  244.000000  244.000000
mean     0.350145    0.313934
std      0.186477    0.190220
min      0.000000    0.000000
25%      0.215281    0.200000
50%      0.308442    0.200000
75%      0.441087    0.400000
max      1.000000    1.000000

## When Does a Dataset Need Normalization?

A dataset does **not** inherently need normalization. Normalization becomes necessary **only in specific modeling contexts**, depending on how algorithms interpret numerical feature values.

---

## Why We Normalize Data

Normalization is performed to:

- Bring numerical features to a **common scale**
- Prevent features with large magnitudes from **dominating distance calculations**
- Improve **numerical stability** during optimization
- Ensure **fair feature contribution** in similarity-based models
- Accelerate **model convergence** in iterative algorithms

Normalization does **not** add information to the data; it only changes how the model *perceives* existing information.

---

## When Normalization Is Required in the ML Workflow

Normalization is typically applied **after train–test split** and **before model training**, when the following conditions are met:

### 1. The algorithm is distance-based
Normalization is required when the model computes distances or similarities.

Examples:
- K-Nearest Neighbors (KNN)
- K-Means clustering
- DBSCAN
- Models using cosine similarity

---

### 2. The algorithm uses gradient-based optimization
Normalization improves convergence speed and stability.

Examples:
- Linear Regression (gradient descent)
- Logistic Regression
- Support Vector Machines
- Neural Networks

---

### 3. Features have significantly different scales
Normalization is needed when features differ by orders of magnitude.

Example:
- Age: 18–60
- Income: 20,000–2,000,000

Without normalization, larger-scale features dominate learning.

---

### 4. Inputs must be bounded
Some models perform better or require inputs within a fixed range.

Examples:
- Neural networks
- Image data (pixel values scaled to [0, 1])
- Regularized models with bounded assumptions

---

## When Normalization Is NOT Needed

Normalization is generally unnecessary when:

- Using tree-based models:
  - Decision Trees
  - Random Forests
  - Gradient Boosting
- Features are already on comparable scales
- The model relies on rule-based splits rather than distances

---

## Normalization in the ML Workflow (Order Matters)

1. Split data into **train and test sets**
2. Fit normalization **only on training data**
3. Transform both train and test data using the same parameters
4. Train the model on normalized training data

---

## Key Takeaway

> **We normalize data when the algorithm is sensitive to feature scale, not because the dataset itself demands it.**

Normalization is a **tool**, not a default requirement.

In [117]:
from sklearn.preprocessing import StandardScaler
# Initialize StandardScaler
std_scaler = StandardScaler()

# Apply standardization
standardized_array = std_scaler.fit_transform(num_df)

# Convert to DataFrame for readability
standardized_df = pd.DataFrame(
    standardized_array,
    columns=num_df.columns
)

standardized_df.head()

   total_bill      size
0   -0.314711 -0.600193
1   -1.063235  0.453383
2    0.137780  0.453383
3    0.438315 -0.600193
4    0.540745  1.506958

In [118]:
print(standardized_df.describe())

         total_bill          size
count  2.440000e+02  2.440000e+02
mean  -7.871663e-17 -5.824121e-17
std    1.002056e+00  1.002056e+00
min   -1.881547e+00 -1.653768e+00
25%   -7.247111e-01 -6.001926e-01
50%   -2.241005e-01 -6.001926e-01
75%    4.886857e-01  4.533829e-01
max    3.492068e+00  3.614110e+00

In [119]:
comparison_df = pd.concat(
    [num_df.head(), standardized_df.head()],
    axis=1,
    keys=["Original", "Standardized"]
)

print(comparison_df)

    Original      Standardized
  total_bill size   total_bill      size
0      16.99    2    -0.314711 -0.600193
1      10.34    3    -1.063235  0.453383
2      21.01    3     0.137780  0.453383
3      23.68    2     0.438315 -0.600193
4      24.59    4     0.540745  1.506958

In [120]:
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(
    num_df,
    test_size=0.2,
    random_state=42
)

# Fit only on training data
std_scaler = StandardScaler()
X_train_scaled = std_scaler.fit_transform(X_train)

# Transform test data using training parameters
X_test_scaled = std_scaler.transform(X_test)

In [121]:
print(pd.DataFrame(X_train_scaled, columns=num_df.columns).describe())

         total_bill          size
count  1.950000e+02  1.950000e+02
mean   1.013434e-16 -1.047595e-16
std    1.002574e+00  1.002574e+00
min   -1.653831e+00 -1.677921e+00
25%   -7.496230e-01 -6.121407e-01
50%   -2.626538e-01 -6.121407e-01
75%    5.301000e-01  4.536400e-01
max    3.497068e+00  3.650982e+00

## When Does a Dataset Need Scaling?

A dataset does **not** inherently need scaling. Scaling becomes necessary **only when the learning algorithm is sensitive to feature magnitude or variance**, and when numerical features exist on different units or ranges.

---

## Why We Scale Data

Scaling is performed to:

- Align feature magnitudes so no single feature dominates learning
- Improve **numerical stability** in optimization
- Speed up **convergence** in gradient-based algorithms
- Make model coefficients **comparable and interpretable**
- Ensure fair contribution of all features during learning

Scaling changes the **scale and variance** of features but preserves their relative structure.

---

## When Scaling Is Required in the ML Workflow

Scaling is typically applied **after train–test split** and **before model training**, under the following conditions:

### 1. The algorithm is gradient-based
Scaling stabilizes and accelerates gradient descent.

Examples:
- Linear Regression
- Logistic Regression
- Support Vector Machines
- Neural Networks

---

### 2. The algorithm depends on variance or distance
Scaling prevents high-variance features from dominating.

Examples:
- K-Nearest Neighbors (KNN)
- K-Means clustering
- PCA (variance-based)
- SVM with RBF or polynomial kernels

---

### 3. Features are measured in different units
Scaling is necessary when features represent different physical quantities.

Example:
- Height (cm)
- Weight (kg)
- Income (₹)

Without scaling, larger-unit features disproportionately influence learning.

---

### 4. Regularization is applied
Scaling ensures regularization penalizes all features equally.

Examples:
- Ridge Regression
- Lasso Regression
- ElasticNet

---

## When Scaling Is NOT Needed

Scaling is generally unnecessary when:

- Using tree-based models:
  - Decision Trees
  - Random Forests
  - Gradient Boosting
- Features already have similar ranges and units
- The algorithm relies on threshold-based splits

---

## Scaling in the ML Workflow (Order Matters)

1. Split data into **training and test sets**
2. Fit the scaler **only on training data**
3. Transform both training and test data using the same scaler
4. Train the model on scaled training data

---

## Key Takeaway

> **We scale data when the algorithm is sensitive to feature magnitude or variance, not because the dataset itself demands it.**

Scaling is a **preprocessing choice driven by the model**, not a mandatory step.

---
---
---


---

### Are the conditions for scaling and normalization the same?

**Yes — at a high level.**
Both are applied when the **algorithm is sensitive to feature scale**.

**But the choice between them depends on *how* the algorithm uses the data.**

---

### When to use **MinMaxScaler (Normalization)**

Use **Min–Max scaling** when:

* You need features in a **fixed bounded range** (usually [0, 1])
* The model **expects or benefits from bounded inputs**
* The data does **not contain extreme outliers**
* Preserving relative distances is important

Typical use cases:

* Neural networks
* Image data (pixel scaling)
* KNN / K-Means when no strong outliers
* Models using sigmoid or tanh activations

---

### When to use **StandardScaler (Standardization)**

Use **StandardScaler** when:

* The algorithm assumes **zero mean and unit variance**
* Data is approximately **Gaussian**
* Outliers are meaningful and should not be clipped
* You are using **regularization or gradient descent**

Typical use cases:

* Linear Regression
* Logistic Regression
* SVM
* PCA
* Regularized models (Ridge, Lasso)

---

### One-line decision rule (interview-safe)

> **Use MinMaxScaler when bounded ranges matter; use StandardScaler when variance and distribution matter.**

That is the cleanest and most accurate distinction.

# Encoding categorical data

In [122]:
import seaborn as sns 
import pandas as pd

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [123]:
X = df.drop(columns=["tip"])
y = df["tip"]

X.head()

   total_bill     sex smoker  day    time  size
0       16.99  Female     No  Sun  Dinner     2
1       10.34    Male     No  Sun  Dinner     3
2       21.01    Male     No  Sun  Dinner     3
3       23.68    Male     No  Sun  Dinner     2
4       24.59  Female     No  Sun  Dinner     4

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [125]:
numeric_features = X.select_dtypes(include=["float64", "int64"]).columns
categorical_features = X.select_dtypes(include=["category"]).columns

print("Numeric:", numeric_features)
print("Categorical", categorical_features)

Numeric: Index(['total_bill', 'size'], dtype='object')
Categorical Index(['sex', 'smoker', 'day', 'time'], dtype='object')

In [126]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [127]:
numeric_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

### combine pipeline using ColumnTransformer

In [128]:
preprocessor = ColumnTransformer(
    transformers=[
        ("nums", numeric_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

In [129]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [130]:
from sklearn.linear_model import LinearRegression

model = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("regression",LinearRegression())
])

In [131]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('nums',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['total_bill', 'size'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['sex', 'smoker', 'day', 'time'], dtype='object'))])),
                ('regression', LinearRegression())])

## Without any pipeline

In [132]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [133]:
categorical_cols = df.select_dtypes(include=["object", "category"]).columns
categorical_cols

Index(['sex', 'smoker', 'day', 'time'], dtype='object')

In [134]:
encoded_df = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=False,
    dtype=int
)
encoded_df.head()

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,0,1,0,1,0,0,0,1,0,1
1,10.34,1.66,3,1,0,0,1,0,0,0,1,0,1
2,21.01,3.50,3,1,0,0,1,0,0,0,1,0,1
3,23.68,3.31,2,1,0,0,1,0,0,0,1,0,1
4,24.59,3.61,4,0,1,0,1,0,0,0,1,0,1

In [135]:
print("Original columns:")
print(df.columns)

print("\nEncoded columns:")
print(encoded_df.columns)

Original columns:
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

Encoded columns:
Index(['total_bill', 'tip', 'size', 'sex_Male', 'sex_Female', 'smoker_Yes',
       'smoker_No', 'day_Thur', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Lunch',
       'time_Dinner'],
      dtype='object')

In [136]:
X_encoded = encoded_df.drop(columns=["tip"])
y = encoded_df["tip"]

In [137]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

# without pipeline 2

In [138]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [139]:
categorical_cols = df.select_dtypes(include=["object", "category"]).columns
categorical_cols

Index(['sex', 'smoker', 'day', 'time'], dtype='object')

In [140]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

In [141]:
encoded_array = ohe.fit_transform(df[categorical_cols])
encoded_array

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [142]:
encoded_feature_names = ohe.get_feature_names_out(categorical_cols)
encoded_feature_names

array(['sex_Female', 'sex_Male', 'smoker_No', 'smoker_Yes', 'day_Fri',
       'day_Sat', 'day_Sun', 'day_Thur', 'time_Dinner', 'time_Lunch'],
      dtype=object)

### Why `get_feature_names_out()` Is Used

`OneHotEncoder` converts categorical features into a NumPy array, which does not retain column names.  
`get_feature_names_out()` is used to retrieve the automatically generated feature names for each encoded category, allowing the encoded output to be interpreted, labeled, and converted back into a pandas DataFrame.

In [143]:
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoded_feature_names,
    index=df.index
)

encoded_df.head()

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [144]:
numeric_df = df.select_dtypes(include=["int64", "float64"])

final_df = pd.concat([numeric_df, encoded_df], axis=1)
final_df.head()

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,10.34,1.66,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,21.01,3.50,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,23.68,3.31,2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,24.59,3.61,4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

# Feature Selection

## Feature Selection — Intuition

Feature selection is the process of identifying and retaining a subset of relevant features that contribute meaningfully to a machine learning model’s predictive performance, while removing features that are irrelevant, redundant, or noisy. The objective of feature selection is to improve model effectiveness rather than to reduce dimensionality arbitrarily.

---

## Purpose of Feature Selection

Including a large number of features does not guarantee better performance. In many cases, unnecessary features can negatively affect learning by introducing noise and complexity. Feature selection aims to improve model quality by simplifying the feature space.

---

## Why Feature Selection Is Important

Feature selection helps to:

- Reduce overfitting by eliminating noise-driven features  
- Improve generalization to unseen data  
- Decrease training and inference time  
- Enhance model interpretability  
- Stabilize model behavior across datasets  

---

## Types of Uninformative Features

### 1. Irrelevant Features
Features that have no meaningful relationship with the target variable.  
Example: a customer ID used to predict product price.

---

### 2. Redundant Features
Features that convey duplicate information already captured by other features.  
Example: height measured in centimeters and meters.

---

### 3. Noisy Features
Features that contain weak or inconsistent patterns and add random variation to the data.

---

## How Feature Selection Affects Learning

By removing unhelpful features, the model can:

- Focus on informative signals  
- Learn simpler and more robust decision boundaries  
- Produce more stable and reliable predictions  

This is particularly important for linear models, distance-based algorithms, and datasets with high dimensionality.

---

## Feature Selection vs Feature Extraction

- **Feature selection** involves choosing a subset of existing features.
- **Feature extraction** involves creating new features from the original data (e.g., PCA).

Feature selection preserves the original meaning and interpretability of features.

---

## When Feature Selection Is Most Useful

Feature selection is especially beneficial when:

- The dataset has a large number of features  
- The dataset is small relative to the number of features  
- Model interpretability is important  
- The model is sensitive to noise and overfitting  

---

## Key Takeaway

> Feature selection improves model performance by removing irrelevant and redundant features, allowing the model to learn from the most informative inputs only.

# Feature selection (Code)

In [145]:
import seaborn as sns
import pandas as pd 

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [146]:
df_encoded = pd.get_dummies(df, drop_first=True, dtype=int)
df_encoded.head()

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16.99,1.01,2,1,1,0,0,1,1
1,10.34,1.66,3,0,1,0,0,1,1
2,21.01,3.50,3,0,1,0,0,1,1
3,23.68,3.31,2,0,1,0,0,1,1
4,24.59,3.61,4,1,1,0,0,1,1

In [147]:
X = df_encoded.drop(columns=["tip"])
y = df_encoded["tip"]

In [148]:
correlation = X.corrwith(y).sort_values(ascending=False)
correlation

total_bill     0.675734
size           0.489299
day_Sun        0.125114
time_Dinner    0.121629
day_Sat       -0.002790
smoker_No     -0.005929
day_Fri       -0.055463
sex_Female    -0.088862
dtype: float64

In [149]:
selected_features = correlation[abs(correlation)>0.2].index
selected_features

Index(['total_bill', 'size'], dtype='object')

---
In this context, `.index` returns the column names.

More precisely:

- `correlation` is a Pandas Series

In a Series:
- **Index** → labels (here: feature / column names)
- **Values** → data (here: correlation coefficients)

---
Rule of thumb for interpreting Pearson correlation (absolute value):

* 0.00 to 0.10 → Negligible or no linear relationship
* 0.10 to 0.30 → Weak linear relationship
* 0.30 to 0.50 → Moderate linear relationship
* 0.50 to 1.00 → Strong linear relationship

Notes:

* The sign (+ or −) indicates direction, not strength.
* Strength is determined by the absolute value of the correlation.
* These ranges are heuristic guidelines, not strict statistical rules.
* The appropriate threshold depends on the dataset and the model being used.

In [150]:
X_selected = X[selected_features]
X_selected.head()

   total_bill  size
0       16.99     2
1       10.34     3
2       21.01     3
3       23.68     2
4       24.59     4

In [151]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, 
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [152]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.4811084097989491

# Same code with pipeline

In [153]:
import seaborn as sns
import pandas as pd 
import numpy as np 

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [154]:
df = sns.load_dataset("tips")
df_encoded = pd.get_dummies(df, drop_first=True, dtype=int)

In [155]:
X = df_encoded.drop(columns=["tip"])
y = df_encoded["tip"]

In [156]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [157]:
class CorrelationSelector(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.2):
        self.threshold = threshold
        
    
    def fit(self,x,y):
        corr = pd.DataFrame(X).corrwith(y)
        self.selected_features_ = corr[abs(corr) >self.threshold].index
        return self 
    
    def transform(self,X):
        return X[self.selected_features_]

pipeline = Pipeline(steps=[
    ("feature_selection", CorrelationSelector(threshold=0.2)),
    ("regression", LinearRegression())
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('feature_selection', CorrelationSelector()),
                ('regression', LinearRegression())])

In [158]:
from sklearn.metrics import r2_score
y_pred = pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.4811084097989491

# Remove Irrelevant Features

## Baseline Evaluation (Before Removing Anything)

In [159]:
from sklearn.metrics import root_mean_squared_error

baseline_rmse = root_mean_squared_error(y_test, y_pred)
print("Baseline RMSE", baseline_rmse)

Baseline RMSE 0.8053568271607012

## Remove a Potentially Redundant Feature

In [161]:
# Drop 'size'
X_reduced = X.drop(columns=["size"])

# Recreate train-test split
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reduced, y,
    test_size=0.2,
    random_state=42
)

# Recreate preprocessing
numeric_features_r = X_reduced.select_dtypes(include=["float64", "int64"]).columns
categorical_features_r = X_reduced.select_dtypes(include=["category"]).columns

numeric_pipeline_r = Pipeline(steps=[
    ("scaler", StandardScaler())
])

categorical_pipeline_r = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_r = ColumnTransformer(
    transformers=[
        ("nums", numeric_pipeline_r, numeric_features_r),
        ("cat", categorical_pipeline_r, categorical_features_r)
    ]
)

# Rebuild model
model_r = Pipeline(steps=[
    ("preprocessing", preprocessor_r),
    ("regression", LinearRegression())
])

# Train
model_r.fit(X_train_r, y_train_r)

# Evaluate
y_pred_r = model_r.predict(X_test_r)
rmse_r = root_mean_squared_error(y_test_r, y_pred_r)

print("RMSE after removing 'size':", rmse_r)

RMSE after removing 'size': 0.8082620065870569

# another pipeline version

In [ ]:
import seaborn as sns 
import pandas as pd 

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df_encoded = pd.get_dummies(df, drop_first=True, dtype=int)
df_encoded.head()

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16.99,1.01,2,1,1,0,0,1,1
1,10.34,1.66,3,0,1,0,0,1,1
2,21.01,3.50,3,0,1,0,0,1,1
3,23.68,3.31,2,0,1,0,0,1,1
4,24.59,3.61,4,1,1,0,0,1,1

In [ ]:
X = df_encoded.drop(columns=["tip"])
y = df_encoded["tip"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size =0.2,
    random_state =42
)
selected_features = correlation[abs(correlation) > 0.2].index
selected_features

Index(['total_bill', 'size'], dtype='object')

In [ ]:
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [ ]:
pipeline = Pipeline(steps=[
    ("feature_selection", SelectKBest(score_func=f_regression, k=5)),
    ("regression", LinearRegression())
])

In [ ]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('feature_selection',
                 SelectKBest(k=5,
                             score_func=<function f_regression at 0x7f79d4584180>)),
                ('regression', LinearRegression())])

In [ ]:
from sklearn.metrics import r2_score

y_pred = pipeline.predict(X_test)
r2_score(y_test,y_pred)

0.46657759378278885

In [ ]:
selected_mask = pipeline.named_steps["feature_selection"].get_support()
selected_features = X_train.columns[selected_mask]

selected_features

Index(['total_bill', 'size', 'sex_Female', 'day_Sun', 'time_Dinner'], dtype='object')

In [ ]:
nums = [10,20,30,40]
first = nums.pop(nums.index(min(nums)))
nums

[20, 30, 40]